### ISSUE TITLE
the connect to metamask doesn't work

### ISSUE THREAD

**Issue by giwaov** [beyond-btc/community#107]
### Contact details

giwavictor9@gmail.com

### What happened?

When i clicked on connect metamask, it doesnt connect. i tried it several times and even cleared cache but still the same . the button is just unresponsive 
![Screenshot 2024-10-18 1430595](https://github.com/user-attachments/assets/7621076f-aa30-462a-af9d-fa578bfd91a3)

### On which browser(s) did you encounter the issue?

Chrome, Metamask

**Comment by sunnybeyond** [comment]
Not enough info to create a case.
