### ISSUE TITLE
added Feature 

### ISSUE THREAD

**Issue by cruzlx** [beyond-btc/community#111]
### Contact details

https://x.com/fauzanhl_

### Is your feature request related to a problem? Please explain.

I think you should add the amount to the recipient's btc address or whatever, runes tapoot or other btc ecosystem, so that there is no mistake about the price and nominal for users, and add a transaction history feature that allows users to see the results of their tx
![Screenshot (325)](https://github.com/user-attachments/assets/0f6ab9f2-1c21-4a14-bff2-9e2f0c1007f5)

### Describe the solution you'd like

added appropriate price for recipient address and added tx history feature

**Comment by sunnybeyond** [comment]
There is already a transaction history. Don't know what you mean with the 1st suggestion.
