### ISSUE TITLE
recycling offer

### ISSUE THREAD

**Issue by ritorisa6l** [beyond-btc/community#112]
### Contact details

destcauper_refs@outlook.com

### Is your feature request related to a problem? Please explain.

Hello, development team!

I haven’t seen anywhere on the site that shows the total balance, and this gave me an idea! Honestly, I don’t know if it’s possible, but it would be fantastic if you could implement this.
![image](https://github.com/user-attachments/assets/ea4bac94-ec7f-429c-80ae-59c00983278c)

### Describe the solution you'd like

The idea is to not only see my overall balance on the site but also to see in which networks and tokens I have funds. Of course, the balance should only be shown for the networks that the swap supports.

**Comment by sunnybeyond** [comment]
Low effort.
