### ISSUE TITLE
cool!

### ISSUE THREAD

**Issue by faujecnadzu3j** [beyond-btc/community#113]
### Contact details

percidua_shik7@hotmail.com

### Is your feature request related to a problem? Please explain.

Greetings! I really liked your swap, everything works well on my tests. Personally, I would like to change the theme of the site (at least by color), as I often use exchangers

### Describe the solution you'd like

Greetings! I really liked your swap, everything works well on my tests. Personally, I would like to change the theme of the site (at least by color), as I often use exchangers

**Comment by sunnybeyond** [comment]
Low effort.
