### ISSUE TITLE
Too short line

### ISSUE THREAD

**Issue by britnecongije** [beyond-btc/community#115]
### Contact details

rorahyd_ta0r@hotmail.com

### What happened?

Hello. I tested the Bitcoin Swaps in the BNB and vice versa, everything is super, but there is one point-the input line is too coral, literally 4-5 digits, because of this it will sometimes be necessary to blow the line to check. Is it possible to increase the length ??

![Uploading 84ca48b8-fd38-42d0-b62b-0a26d1a287f9.jpg…]()

**Comment by britnecongije** [comment]
google chrome

**Comment by w3theo** [comment]
i can't see your screenshot, can you upload somewhere else, for example imgur?

**Comment by sunnybeyond** [comment]
Can't see screenshot, so.
