### ISSUE TITLE
for beginners

### ISSUE THREAD

**Issue by ripenmuspicd** [beyond-btc/community#116]
### Contact details

niscorta_mo10@hotmail.com

### Is your feature request related to a problem? Please explain.

Good afternoon, I want to report that the swap from EVM networks to the bitcoin network does not work, I really wanted to test this particular function, but for some reason the transfer button just lights up in gray and I can't do anything about it. But in general, your site works without any complaints, has made all possible translations and has not noticed any errors! Congratulations, you've done a great job, there's just a little bit left to make it perfect!!!!
![image](https://github.com/user-attachments/assets/b13911f5-6e3c-4d4b-a62c-a4ca13ac9ebe)

### Describe the solution you'd like

 perfect!!!!

**Comment by sunnybeyond** [comment]
Well, you didn't put a receive address nor connect a wallet in the Bitcoin Testnet window. So yes, the button stays gray.
