### ISSUE TITLE
corretion proposal

### ISSUE THREAD

**Issue by protabnecgulq** [beyond-btc/community#118]
### Is your feature request related to a problem? Please explain.

Hey team! Your project looks promising, but it’s hard to really judge it without more test networks available. It would be super helpful if you could add a section with guides for beginners. Also, having approximate fees when selecting a network would be great.

Maybe you could implement a simple FAQ or tutorial section that addresses common questions and shows how to calculate fees. I’m looking forward to when the testnet is available so I can try out all the features!
![image](https://github.com/user-attachments/assets/b2840518-604d-4437-a8ff-348e835aba86)

### Describe the solution you'd like

Hi Beyond Swap team! I really like your idea of connecting different cryptocurrencies. If you can make swapping without using exchanges work, that would be amazing! But I think it would help a lot if you could show a total balance and info about tokens in different networks. 

Perhaps you could integrate a dashboard feature that displays users’ total balances across supported networks. Can’t wait for your mainnet launch!

**Comment by sunnybeyond** [comment]
Please, some more details.
