### ISSUE TITLE
Bug report 

### ISSUE THREAD

**Issue by biodun09** [beyond-btc/community#120]
### Contact details

@olatoyeabiodun76@gmail.com

### What happened?

I tried to connect to my unisat wallet using chrome browser on my iphone but i kept getting “wallet connection error” message 
After loading ‘app.beyond.tech’ i navigated to the top right corner and clicked ‘connect wallet’
I clicked ‘unisat’ as my wallet choice.
Instead of being redirected to unisat wallet on my phone, i got ‘wallet connection error’
![IMG_4280](https://github.com/user-attachments/assets/111ad390-37c2-4d39-84a9-4435426e0f4b)

I have attached a screenshot to illustrate the issue.

### On which browser(s) did you encounter the issue?

Chrome

**Comment by sunnybeyond** [comment]
Not enough info for a case.
