### ISSUE TITLE
addresses

### ISSUE THREAD

**Issue by verconvobac1** [beyond-btc/community#121]
### Contact details

roconma_rudl@hotmail.com

### Is your feature request related to a problem? Please explain.

![image](https://github.com/user-attachments/assets/22557d26-440e-4aa6-a3ba-bba7bdd839c6)
Hello! I checked out your site and it seems cool. But I really hope you can allow sending tokens to different addresses. That would be super convenient, especially for businesses. You might want to consider adding an option for users to enter any wallet address for token transfers, not just their own.

### Describe the solution you'd like

I’m looking forward to seeing more developments in the project, including partnerships with other projects and a full testnet. Good luck!

**Comment by sunnybeyond** [comment]
Any wallet is already possible. Bulk transfer is suggested already in better format.
