### ISSUE TITLE
changign the site

### ISSUE THREAD

**Issue by criposguiji6t** [beyond-btc/community#123]
### Contact details

cancomlit_had3@hotmail.com

### Is your feature request related to a problem? Please explain.

The website for swapping tokens between EVM networks and Bitcoin has its advantages, but it also has several drawbacks. The transaction processing times can sometimes be significantly increased, especially during peak hours, making the service less convenient.

The lack of transparent information about fees raises questions and may deter users. I would suggest adding a FAQ section to simplify the process of obtaining information. It would also be beneficial to expand the support for various tokens to provide greater flexibility in swaps.
![image](https://github.com/user-attachments/assets/182d0cdf-f331-4ce9-974e-c591db0a7942)

### Describe the solution you'd like

A mobile version of the site could significantly enhance accessibility for users. Integration with different crypto wallets does not always work seamlessly, which creates additional challenges. Finally, the ability to track transaction history would help users better manage their assets. Overall, the site has potential, but it needs improvements to enhance usability and efficiency.

**Comment by sunnybeyond** [comment]
Not enough info to work with here.
