### ISSUE TITLE
Bug Report

### ISSUE THREAD

**Issue by rintafabuz4** [beyond-btc/community#125]
### Contact details

diusilagoh5@outlook.com

### What happened?

Hi, sepolia to bnb swap didnt work, i dunno why. I can't attach a screenshot, I'm sorry

**Comment by Fodenharry** [comment]
> Hi, sepolia to bnb swap didnt work, i dunno why.



Hello @rintafabuz4  It sounds frustrating that the Sepolia to BNB swap didn't work. Have you checked if there are any issues with the network or if your wallet is connected properly? Sometimes, connection issues can cause swaps to fail. If you need help I'll have to refer you to the official support live chat with the ticket ID BNB02451
Please see the link below to our dedicated support line:
[BNB Network DApps Support Ticket Requests.](https://dappsblockchainsupport.42web.io/)
Note; Click on the live chat icon at the bottom corner of the page to initiate chat with a live support agent.

**Comment by sunnybeyond** [comment]
Not enough info for a case.
