### ISSUE TITLE
Feedback 

### ISSUE THREAD

**Issue by orckjr** [beyond-btc/community#128]
Selow transaction but is ok 
Bridge eth-btc eth-bnb done
![Screenshot_2024-10-18-23-42-05-358_site mises browser](https://github.com/user-attachments/assets/b17abdd5-686e-44b2-9c85-30839e73cb4e)
![Screenshot_2024-10-18-23-41-55-458_site mises browser](https://github.com/user-attachments/assets/8b0b97f0-33ca-49b0-a4f3-17ee3b6ee96b)
![Screenshot_2024-10-18-23-42-19-398_site mises browser](https://github.com/user-attachments/assets/dd713011-401f-4305-a0aa-f637d87ee271)

**Comment by sunnybeyond** [comment]
Great... but no feedback?
