### ISSUE TITLE
BUG

### ISSUE THREAD

**Issue by winteriscomingg** [beyond-btc/community#129]
### Contact details

@sandwichh0x8

### What happened?

1) Cant use the metermask desktop extension to connect wallet 

2) While using bnb network to btc cant find tbnb only TON,Bbtc and eth 

after serval wallet connect cant seems to connect my wallet to the website

I have attached a screenshot to illustrate the issue.
<img width="1169" alt="Screenshot 2024-10-18 at 5 19 33 PM" src="https://github.com/user-attachments/assets/df7070ed-328b-4e2f-8539-d0847661603e">

**Comment by sunnybeyond** [comment]
Not enough info for a case.
