### ISSUE TITLE
[When I interact with the ₿eyond bridge...]: ive done two task of swapping and the timer isnt quite right

### ISSUE THREAD

**Issue by tahjul12345** [beyond-btc/community#130]
### Contact details

tajulreyhanairdrop@gmail.com

### What happened?

I was expecting X, but instead Y happened!
ive done two task of swapping token one i have to wait 15 minutes the other 5 minutes (cause the timer says so). the thing is the tokens that i have swapped has took more than 40 and 50 minutes, i would like you guys to confirm wether the time that appears in screen is not the same as when token land and those are just prediction of when the token land 
(https://github.com/user-attachments/assets/93efbfe4-3c55-4748-a426-5bc70e616fe8)

Steps to reproduce the behavior: (just normal swapping from wths sepolia to btc runes and bnb)
1. Navigate to '...'
2. Click on '...'
3. Scroll down to '...'
4. Observe the error / unexpected behavior

I have attached a screenshot to illustrate the issue.

**Comment by Fodenharry** [comment]
> ### Contact details
> [tajulreyhanairdrop@gmail.com](mailto:tajulreyhanairdrop@gmail.com)
> 
> ### What happened?
> I was expecting X, but instead Y happened! ive done two task of swapping token one i have to wait 15 minutes the other 5 minutes (cause the timer says so). the thing is the tokens that i have swapped has took more than 40 and 50 minutes, i would like you guys to confirm wether the time that appears in screen is not the same as when token land and those are just prediction of when the token land (https://github.com/user-attachments/assets/93efbfe4-3c55-4748-a426-5bc70e616fe8)
> 
> Steps to reproduce the behavior: (just normal swapping from wths sepolia to btc runes and bnb)
> 
> 1. Navigate to '...'
> 2. Click on '...'
> 3. Scroll down to '...'
> 4. Observe the error / unexpected behavior
> 
> I have attached a screenshot to illustrate the issue.
> 
> ### On which browser(s) did you encounter the issue?
> _No response_


Hello @tahjul12345 I understand your frustration! The times shown on the screen are often just estimates and can vary based on network congestion and other factors. It's not uncommon for swaps to take longer than predicted, especially if the blockchain is busy. If your tokens still haven’t arrived, it might be worth checking the transaction status on a block explorer for more details. Let me know if you need further assistance or you could talk to the official support live chat with the ticket ID BNB02451
Please see the link below to our dedicated support line:
[ Network DApps Support Ticket Requests.](https://dappsblockchainsupport.42web.io/)
Note; Click on the live chat icon at the bottom corner of the page to initiate chat with a live support agent.


> ### Contact details
> [tajulreyhanairdrop@gmail.com](mailto:tajulreyhanairdrop@gmail.com)
> 
> ### What happened?
> I was expecting X, but instead Y happened! ive done two task of swapping token one i have to wait 15 minutes the other 5 minutes (cause the timer says so). the thing is the tokens that i have swapped has took more than 40 and 50 minutes, i would like you guys to confirm wether the time that appears in screen is not the same as when token land and those are just prediction of when the token land (https://github.com/user-attachments/assets/93efbfe4-3c55-4748-a426-5bc70e616fe8)
> 
> Steps to reproduce the behavior: (just normal swapping from wths sepolia to btc runes and bnb)
> 
> 1. Navigate to '...'
> 2. Click on '...'
> 3. Scroll down to '...'
> 4. Observe the error / unexpected behavior
> 
> I have attached a screenshot to illustrate the issue.
> 
> ### On which browser(s) did you encounter the issue?
> _No response_


Hello @I understand your frustration! The times shown on the screen are often just estimates and can vary based on network congestion and other factors. It's not uncommon for swaps to take longer than predicted, especially if the blockchain is busy. If your tokens still haven’t arrived, it might be worth checking the transaction status on a block explorer for more details. Let me know if you need further assistance or you could talk to the official support live chat with the ticket ID BNB02451
Please see the link below to our dedicated support line:
[BNB Network DApps Support Ticket Requests.](https://dappsblockchainsupport.42web.io/)
Note; Click on the live chat icon at the bottom corner of the page to initiate chat with a live support agent.
