### ISSUE TITLE
[Enhance the ₿eyond UI with...]: transaction time!

### ISSUE THREAD

**Issue by nabrouke** [beyond-btc/community#132]
### Contact details

x.com/nabrouke

### Is your feature request related to a problem? Please explain.

Good evening, there is not enough time stamp for the transaction, even an approximate one. I propose to make the transaction progress time because all networks allow you to find out + - what time is needed for this, in the next post I will attach a screenshot of how you can do this

### Describe the solution you'd like

I propose to do it aesthetically without doing anything unnecessary. just in black font. my wallet bc1p3rj3nncsn8huvwdasp7n05hv62s5ptj92vp4eu2y6nk0rpx3kd2st9a0mf

**Comment by sunnybeyond** [comment]
There is a timestamp in the history window...
