### ISSUE TITLE
I can't make a bridge

### ISSUE THREAD

**Issue by ramilyarullin** [beyond-btc/community#133]
### Contact details

rarullin20@gmail.com

### What happened?

I expected to see a working button, but instead the bridge button was gray!

1. Connecting meta mask and unisat wallets
2. Click on the sepolia test net and select the amount of ether
3. Scroll down to the bridge button
4. Please note that it is gray. I can't click on it.

I have attached a screenshot illustrating the problem.
<img width="929" alt="Снимок экрана 2024-10-18 в 21 19 07" src="https://github.com/user-attachments/assets/7fa35027-2c18-4327-af31-eb5086c965c1">
<img width="929" alt="Снимок экрана 2024-10-18 в 21 19 07" src="https://github.com/user-attachments/assets/671b38db-5a0d-4a1f-8e56-a7775792ce69">

### On which browser(s) did you encounter the issue?

Chrome

**Comment by sunnybeyond** [comment]
You try to send to a BTC mainnet wallet instead of testnet.
