### ISSUE TITLE
i can't do it. no bridge

### ISSUE THREAD

**Issue by zikolodjis** [beyond-btc/community#134]
### Contact details

@Carol947326420

### What happened?

I expected to see a working button, but it is no working!

1. Connecting metamask 0xA11d7cb98Dd1C5533eac809544a7Df1Cfd1d4cd2 and unisat wallets bc1qgdaz36p90juechcwzfwgjf0ydgav0q05q7h767
2. Click on the sepolia test net and select the amount of eth test token
3. Scroll down to the bridge button
4. but it is gray. why  I can't click on it. i dont understand
<img width="953" alt="Снимок экрана 2024-10-18 в 21 42 49" src="https://github.com/user-attachments/assets/875c12e1-8c3e-4f6c-b45f-47ea904cf28f">

I have attached a screenshot illustrating the problem.

### On which browser(s) did you encounter the issue?

Chrome

**Comment by sunnybeyond** [comment]
Duplicate? Eitherway, you try to send to btc mainnet wallet instead of testnet.
