### ISSUE TITLE
testnet bridging challange

### ISSUE THREAD

**Issue by ashtagmujib** [beyond-btc/community#151]
### Is your feature request related to a problem? Please explain.

love the UI, looks smooth and user friendly.
after multiple trials i still I found it challenging to bridge my Sepolia testnet token to BNB, kept getting error messages. 

![Screenshot 2024-10-19 093157](https://github.com/user-attachments/assets/fc3b338d-fb31-44a7-aa65-92a93aeb2e3f)
![Screenshot 2024-10-19 093214](https://github.com/user-attachments/assets/421ff597-4f95-4a30-85da-0d87c0b16ad0)

### Describe the solution you'd like

adding an help section that outlines the steps to bridging would go a long way for beginners

**Comment by Fodenharry** [comment]
> ### Contact details
> _No response_
> 
> ### Is your feature request related to a problem? Please explain.
> love the UI, looks smooth and user friendly. after multiple trials i still I found it challenging to bridge my Sepolia testnet token to BNB, kept getting error messages.
> 
> ![Screenshot 2024-10-19 093157](https://private-user-images.githubusercontent.com/121867492/378064426-fc3b338d-fb31-44a7-aa65-92a93aeb2e3f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkzMzU4NjAsIm5iZiI6MTcyOTMzNTU2MCwicGF0aCI6Ii8xMjE4Njc0OTIvMzc4MDY0NDI2LWZjM2IzMzhkLWZiMzEtNDRhNy1hYTY1LTkyYTkzYWViMmUzZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAxOVQxMDU5MjBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kNjcyNDk3ZmU0OWQ5OTVmOTIwYWU2ODA5YjA1MjIzZGZlNmExOGE2YmU2NTMwZjE1NTE5M2QyZTRhNmJkNTRkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.4Ui-MDjWr5gwtSs3GhG-djaHd2SbPAsMNs_9B9FYFq4) ![Screenshot 2024-10-19 093214](https://private-user-images.githubusercontent.com/121867492/378064428-421ff597-4f95-4a30-85da-0d87c0b16ad0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkzMzU4NjAsIm5iZiI6MTcyOTMzNTU2MCwicGF0aCI6Ii8xMjE4Njc0OTIvMzc4MDY0NDI4LTQyMWZmNTk3LTRmOTUtNGEzMC04NWRhLTBkODdjMGIxNmFkMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAxOVQxMDU5MjBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mMzA3NzlhMWRmNDI4NGVhYWRjOTE1MzU1NmY0Zjg3ZWM3NWJmMjcyODU5ZDQyYjhlODYyNzlkNTQ4MmU4MzJmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.u-G9kBPfdOE1XY-WXHCufoQldhsMh390q-qJpV2bExo)
> 
> ### Describe the solution you'd like
> adding an help section that outlines the steps to bridging would go a long way for beginners


Hello @ashtagmujib The UI is pretty nice! 😄 Bridging tokens can be tricky sometimes. Those error messages can be super frustrating! Have you checked if there are any specific requirements or limits for the Sepolia testnet? Sometimes, it helps to double-check if everything's set up right. I can let me know if you need help

**Comment by ashtagmujib** [comment]
apperently i had the wrong wallet signed in on beyond.
ive resolved the issue already tho thank
