### ISSUE TITLE
Feedback About Beyond Bridge

### ISSUE THREAD

**Issue by achuammu** [beyond-btc/community#152]
Name: BIJO GEORGE
Wallet 
Testnet EVM wallet: 0x7d39522cce8312e29ac57db307f93fab57d810dc
Testnet BTC wallet: tb1qpqxcqvh72cxnarswaq4jvf83hvysgsttgnzxfp

**Ordinal Wallet: bc1pl3jl7pj34lyvwcelvlnkll3k2vaw0xs26lye0kpxdmg4n8v64qusny8qmx**

======**FEEDBACK**======
===**INTERFACE**===
The interface of beyond bridge is not looking good. It's looking like very simple. Now a days many projects are coming to market like mushrooms. So most of the customers take a decision after visiting the site. If site is not looking professional, it will make a bad impact on their mid. So make some professional looking in interface.

===**BRIDGE**=== 
1. Transactions are taking more time than expected. If it compare to the other platform, it's very more.
2.  When i select the BNB chain, there i can't get the option of BNB bridge. If we set a network to bridge in our project, make sure to give an option to bridge there native token. Please its better to add BNB for bridge.
3. Most of the transactions are failure

====**_Main Problem in Bridge_**===
After the each of the transaction, we need to connect wallets for more bridge. It will take time. So please solve this issue. Because time is important.

====**My Suggestions**===
1. Please add more facility in bride. It means some unique. It means don't focus only on bridge. People looking more facility in under one project. Add option to send other address our bridged token. Give facility to add some code option to the user when bridge, it will help to claim other user to take that token from your site with the help of site, it will give more security. 
2. Add swap option.
3. Add pointing system according to the transaction, volume, daily use
.

===**MY WISHES**===
**_Success requires a lot of hard work with a good attitude. the team has used both to achieve great things, and I can't wait to see what the team does next. Good luck BEYOND TEAM_**

**Comment by sunnybeyond** [comment]
Wide range of suggestions, but no specific links to platforms that are seemingly better or issues that occured. Sadly, can't do much with this. Cannot reproduce it myself.
