### ISSUE TITLE
You need to work on the crossbridge  The bridge from sepolia to btc is not working. It’s highlighting the button

### ISSUE THREAD

**Issue by damoarewa** [beyond-btc/community#158]
### Contact details

https://twitter.com/damoarewa

### What happened?

I was expecting X, but instead Y happened!

1. Navigate to '.sepolia eth'
2. Click on 'btc address '
3. Scroll down to 'bridge eth'
4. Observe the error / unexpected behavior

I have attached a screenshot to illustrate
![IMG_8133](https://github.com/user-attachments/assets/5a4d411d-1347-4658-8c11-dc6435024e81)
 the issue.

### On which browser(s) did you encounter the issue?

Metamask

**Comment by sunnybeyond** [comment]
Need to select testnet in the btc wallet.
