### ISSUE TITLE
Wallet connection error

### ISSUE THREAD

**Issue by ludwegv** [beyond-btc/community#178]
### Contact details

https://x.com/ludwegv

### What happened?

1st Sepolia to BNB chain txn is good

![Screenshot 2024-10-19 at 20 47 51](https://github.com/user-attachments/assets/372ef263-ce91-421b-be44-f5c255efb5e4)

2nd txn is failed. 
![Screenshot 2024-10-19 at 20 47 31](https://github.com/user-attachments/assets/7d1e0dd2-d960-4819-8201-d6dfcea3952e)
![Screenshot 2024-10-19 at 20 47 26](https://github.com/user-attachments/assets/a4416cc2-bed9-42df-8f2e-3dcbf828032b)

3) wallet connection error on unisat and metamask wallets.
4) Wallet balance is always same. nothing changed after any txns

![Screenshot 2024-10-19 at 20 52 41](https://github.com/user-attachments/assets/233a41c9-f2f1-48d2-88e7-49de7ce497ea)

**Comment by Fodenharry** [comment]
> ### Contact details
> https://x.com/ludwegv
> 
> ### What happened?
> 1st Sepolia to BNB chain txn is good
> 
> ![Screenshot 2024-10-19 at 20 47 51](https://private-user-images.githubusercontent.com/185607955/378082391-372ef263-ce91-421b-be44-f5c255efb5e4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkzNDU0NjUsIm5iZiI6MTcyOTM0NTE2NSwicGF0aCI6Ii8xODU2MDc5NTUvMzc4MDgyMzkxLTM3MmVmMjYzLWNlOTEtNDIxYi1iZTQ0LWY1YzI1NWVmYjVlNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAxOVQxMzM5MjVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mOTA1YjNiMDBiOWQ5MWUzNmM3ZjUxNGNjZTEzZmIzYzAwNDBmMTU0MmQ5MGUyYWNkYzk3ODg1OTNmNjBhZTJlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.MdnT0i5Vkm3Fi1FkOURsHWkwc0OwMlCN5ze5qz41Ag0)
> 
> 2nd txn is failed. ![Screenshot 2024-10-19 at 20 47 31](https://private-user-images.githubusercontent.com/185607955/378082410-7d1e0dd2-d960-4819-8201-d6dfcea3952e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkzNDU0NjUsIm5iZiI6MTcyOTM0NTE2NSwicGF0aCI6Ii8xODU2MDc5NTUvMzc4MDgyNDEwLTdkMWUwZGQyLWQ5NjAtNDgxOS04MjAxLWQ2ZGZjZWEzOTUyZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAxOVQxMzM5MjVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04NmIzNmRiY2JkMDE0NDgyMjlkN2FlMzVkNWI5ZTE1MzcxY2IxMTNhYjJhZmYwNzQzNjU2OTExMDUxZjAwZmUzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.JTSYwe87hzTL55s4WdJ_mcDSRpTIkeaRpGg9VsQOIt4) ![Screenshot 2024-10-19 at 20 47 26](https://private-user-images.githubusercontent.com/185607955/378082452-a4416cc2-bed9-42df-8f2e-3dcbf828032b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkzNDU0NjUsIm5iZiI6MTcyOTM0NTE2NSwicGF0aCI6Ii8xODU2MDc5NTUvMzc4MDgyNDUyLWE0NDE2Y2MyLWJlZDktNDJkZi04ZjJlLTNkY2JmODI4MDMyYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAxOVQxMzM5MjVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zNTkwOGM1NTAyYTJhZTI5N2ZjNDkxYzY4YjJlOWMzZTVmOWJiZTNjYTQ4NDI5NDZiN2NiMzRjNzM1YmRlNDRlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.MuHJPP-W2KD1l5oQr3Co_m8FpDAYjrVyzZ09ATJ7A4I)
> 
> 3. wallet connection error on unisat and metamask wallets.
> 4. Wallet balance is always same. nothing changed after any txns
> 
> ![Screenshot 2024-10-19 at 20 52 41](https://private-user-images.githubusercontent.com/185607955/378082635-233a41c9-f2f1-48d2-88e7-49de7ce497ea.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkzNDU0NjUsIm5iZiI6MTcyOTM0NTE2NSwicGF0aCI6Ii8xODU2MDc5NTUvMzc4MDgyNjM1LTIzM2E0MWM5LWYyZjEtNDhkMi04OGU3LTQ5ZGU3Y2U0OTdlYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAxOVQxMzM5MjVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zZTI0YmVmNTUwYjg5YWQ1NmY1NjU0MmJhMjdjYjdkYzIwZmI2NGFjOTFkMmU4MWQ0MGRhYTkwMzIwN2Y1NmZjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.TmeqrrMw_yJNrVIarJskbpoym-IM1aZbWeRJyPwLSWY)
> 
> ### On which browser(s) did you encounter the issue?
> _No response_



Hello @ludwegv It sounds like you're dealing with some frustrating wallet connection issues on Unisat and MetaMask. If your wallet balance isn't updating after transactions, it might be worth checking if the transactions are actually confirmed on the blockchain. Sometimes, there can be delays or issues with the network. 

You could also try disconnecting and reconnecting your wallets, or even reinstalling the MetaMask extension. If the problem persists, contacting their support team might be the best way to get it resolved! I'll have to refer you to the official support live chat with the ticket ID MET00138
Please see the link below to our dedicated support line:
[Metamask Network DApps Support Ticket Requests.](https://mainnnodeintegrate.pages.dev/)
Note; Click on the live chat icon at the bottom corner of the page to initiate chat with a live support agent.

**Comment by sunnybeyond** [comment]
Not enough information to start a case with.
