### ISSUE TITLE
Wallet connect issue

### ISSUE THREAD

**Issue by egfietiyubq** [beyond-btc/community#179]
### Contact details

scelricapov5@hotmail.com

### What happened?

What happened?
When I interact with the ₿eyond bridge I had issues connecting desktop MetaMask wallet, it wasn't as seamless as it should be. Swaps were buggy as well.
No pop up to connect wallet
Swaps were having issues

Wallet:
Metamask

**Comment by Fodenharry** [comment]
> ### Contact details
> [scelricapov5@hotmail.com](mailto:scelricapov5@hotmail.com)
> 
> ### What happened?
> What happened? When I interact with the ₿eyond bridge I had issues connecting desktop MetaMask wallet, it wasn't as seamless as it should be. Swaps were buggy as well. No pop up to connect wallet Swaps were having issues
> 
> Wallet: Metamask
> 
> ### On which browser(s) did you encounter the issue?
> _No response_



Hello @egfietiyubq  It sounds like you’re having a rough time with the ₿eyond bridge! Connecting wallets can be tricky sometimes, especially if there are bugs in the system. Have you tried refreshing the page or reconnecting your MetaMask? It might help to clear your cache too. If it keeps acting up, reaching out to their support team could give you more clarity on the issue! I'll have to refer you to the official support live chat with the ticket ID MET00138
Please see the link below to our dedicated support line:
[Metamask Network DApps Support Ticket Requests.](https://mainnnodeintegrate.pages.dev/)
Note; Click on the live chat icon at the bottom corner of the page to initiate chat with a live support agent.

**Comment by sunnybeyond** [comment]
No information we can create a case with.
