### ISSUE TITLE
Feature!

### ISSUE THREAD

**Issue by inmagjagi4h** [beyond-btc/community#182]
### Is your feature request related to a problem? Please explain.

![126f2eb7-daa5-437c-b195-299298d563b9](https://github.com/user-attachments/assets/8277c761-7cd7-4840-ba70-5d5122b5c06d)

### Describe the solution you'd like

Hello, beyond, my suggestion to you after I tried the service is to remove the option to select the identical network. I don't know how else to explain, but if I select a swap from btc to btc, the bridge button becomes inactive, and this is logical. But I think we need to add an exception for the identical network

**Comment by sunnybeyond** [comment]
The exception is already there in the sense that the bridge button is inactive. Cleaning up the list is no good, since in the future one might want to send things cross Bitcoin (runes <> ordinals)
