### ISSUE TITLE
[Enhance the ₿eyond UI with...]: Performance Optimization , Transparency 

### ISSUE THREAD

**Issue by Hermad** [beyond-btc/community#184]
### Contact details

ahmadibro51@gmail.com               x.com/@fwahmaddd 

### Is your feature request related to a problem? Please explain.

Yeah. Currently, it takes time to complete transactions, which I believe is too long and could discourage many users from using the service. 

Additionally, I've noticed that the bridge does not display the gas fees associated with transactions. This lack of transparency doesn’t alert users to the costs they will incur, which I think is not ideal for user experience. 

### Describe the solution you'd like

I suggest looking into optimizing the transaction process to reduce the time taken and implementing a feature to show gas fees upfront. I also suggest creating tutorials(videos) and guidelines for new users. Clear, step-by-step(screenshots) instructions would help them understand how to use the bridge effectively, reducing confusion and enhancing their experience. This would greatly enhance the user experience and trust in the platform.

**Comment by sunnybeyond** [comment]
We cannot make transactions faster, this is a limit of the chains, not of the website. Same goes for gas fees. Guides will be available at mainnet release.
