### ISSUE TITLE
Buggy Website

### ISSUE THREAD

**Issue by mmac1234** [beyond-btc/community#185]
### Contact details

x.com/mmactweets

### What happened?

The testnet site gave me some major issues while I was trying to complete the testnet bridges, I claimed all test faucet, but connecting wallet and performing the bridge on the beyond site wasn’t going through, this was dated about 14:00 utc on 19th October, I hope the team can fix this issue, thanks 

### On which browser(s) did you encounter the issue?

Brave

**Comment by sunnybeyond** [comment]
Not enough information to work with. No errors stated, no addresses we can check.
