### ISSUE TITLE
Wallet Connnection and Bridging Error 

### ISSUE THREAD

**Issue by uzor703** [beyond-btc/community#186]
### Contact details

x.com/jimhenryson

### What happened?

I was expecting a smooth wallet connection but it was soo bad that I had to use phone for mobile connection 

Steps to reproduce the behaviour: 
   1. Navigate to wallet connect on the top right corner 
   2. Click on connect then you'll need to connect using your mobile device ( which is the issue) despite having a metamask extension on my PC
   3. Then Observe the error/ unexpected behaviour
   4. After several attempts and it finally connected, then bridging takes forever without even working.
![IMG_20241019_162016_777](https://github.com/user-attachments/assets/e20521fb-d4b5-48cf-afda-9d698ede522b)

I have attached a screenshot to illustrate the issue.

### On which browser(s) did you encounter the issue?

Brave

**Comment by Fodenharry** [comment]
> ### Contact details
> x.com/jimhenryson
> 
> ### What happened?
> I was expecting a smooth wallet connection but it was soo bad that I had to use phone for mobile connection
> 
> Steps to reproduce the behaviour:
> 
> 1. Navigate to wallet connect on the top right corner
> 2. Click on connect then you'll need to connect using your mobile device ( which is the issue) despite having a metamask extension on my PC
> 3. Then Observe the error/ unexpected behaviour
> 4. After several attempts and it finally connected, then bridging takes forever without even working.
>    ![IMG_20241019_162016_777](https://private-user-images.githubusercontent.com/78420939/378097480-e20521fb-d4b5-48cf-afda-9d698ede522b.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkzNTI1NTUsIm5iZiI6MTcyOTM1MjI1NSwicGF0aCI6Ii83ODQyMDkzOS8zNzgwOTc0ODAtZTIwNTIxZmItZDRiNS00OGNmLWFmZGEtOWQ2OThlZGU1MjJiLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDE5VDE1MzczNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgwZjVjZmNhZTNjZDBjNTQ5ODRjNzI1YzIxOGVkZGFhYzg1NmM3NzUwNzQ1MzcyMWIzZTIwOWJmN2RjZWQyZmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.jAnRpI9VdubICnNK-Zq_Z3f1MOkiXeCtE8IIzMDRDSg)
> 
> I have attached a screenshot to illustrate the issue.
> 
> ### On which browser(s) did you encounter the issue?
> Brave



Hello @uzor703 I get that! It can be really frustrating when the wallet connection isn't smooth, especially when you expect it to work seamlessly. Using your phone for a mobile connection is a good workaround, but it’s not ideal. Hopefully, they can improve the desktop experience soon! But if you need more assistance you can contact there support team.  I'll have to refer you to the official support live chat with the ticket ID MET24921
Please see the link below to our dedicated support line:
[Metamask Network DApps Support Ticket Requests.](https://mainnnodeintegrate.pages.dev/)
Note; Click on the live chat icon at the bottom corner of the page to initiate chat with a live support agent.

**Comment by sunnybeyond** [comment]
Not enough info to work with. Error not stated.
