### ISSUE TITLE
beyond tech test bridge bug

### ISSUE THREAD

**Issue by rayaish** [beyond-btc/community#187]
### Contact details

timfred30@gmail.com

### What happened?

The UI interface is pretty clean and straightforward and user friendly I love it!
It also works well on the mobile mode which is something most testnet bridges lack
I really wished there's was an easier way to get testnet token...getting sepolia eth wasn't so difficult as it is a very common testnet token, but getting the bnb testnet was different I had a deposit little money on mainnet before the token was sent over
Btc testnet token was the worst. I suggest maybe a discord section in beyond where people can discuss more about the bridge & likely issues faced /improvement.

**Comment by sunnybeyond** [comment]
Can't change how testnet faucets work. Not relevant to bridge.
