### ISSUE TITLE
very fast transaction dan bug for BTC

### ISSUE THREAD

**Issue by bobby22021997** [beyond-btc/community#189]
Very fast transaction speed
there is a little problem for the btc bridge because the btc token in my wallet is not detected

![Screenshot (122)](https://github.com/user-attachments/assets/0e3761a3-45e7-408a-b8f4-cff3647cbae2)
![Screenshot (121)](https://github.com/user-attachments/assets/11ddd0a5-af62-459d-bf67-030494eb52fe)

**Comment by sunnybeyond** [comment]
Not enough info to work with.
