### ISSUE TITLE
dark mode feature

### ISSUE THREAD

**Issue by tyrodaunt** [beyond-btc/community#192]
### Is your feature request related to a problem? Please explain.

had a wonderful experience bridging eth to bitcoin, love the user interface, super friendly and easy to navigate.
only struggle I had was having to go through this beautiful experience with the bright theme, regardless Im looking forward to bridging more tokens once this goes mainnet.
![Screenshot 2024-10-19 093214](https://github.com/user-attachments/assets/e5ca8fb8-1b31-4557-b8ed-be4e66f874cc)

### Describe the solution you'd like

adding a dark mode feature would be really helpful for users like me that struggles with bright lights on the computer screen.

**Comment by sunnybeyond** [comment]
Low effort.
