### ISSUE TITLE
Transaction History for Completed and Pending Bridges

### ISSUE THREAD

**Issue by kirillh1** [beyond-btc/community#195]
### Contact details

x.com/Akn621224174107

### Is your feature request related to a problem? Please explain.

While using Beyond Bridge, I realized there's no convenient way to access past transaction history directly within the platform. After completing a bridge, it’s difficult to check details or keep track of what’s been done, especially if you’re testing across multiple networks. Having to manually note down transaction details or rely on external tools is inconvenient.

### Describe the solution you'd like

It would be great to have an in-app transaction history feature that shows a list of all completed and pending bridge transactions. This could include simple information like the transaction date, networks involved, and a link to view the transaction on a block explorer. Users could also see pending transactions and their current status (processing, completed, failed).

**Comment by sunnybeyond** [comment]
This feature exists already.
