### ISSUE TITLE
No Connection with Metamask and test possible

### ISSUE THREAD

**Issue by Osi777** [beyond-btc/community#197]
### Contact details

@0si_777

### What happened?

I was expecting to easily connecting my wallet to Beyond Testnet, but instead I cannot connect my wallet. This happens all the time despite I follow the instructions mentioned in your twitter post.

1. Navigate to https://app.beyond.tech/
2. Click on connect

**Comment by Fodenharry** [comment]
> ### Contact details
> @0si_777
> 
> ### What happened?
> I was expecting to easily connecting my wallet to Beyond Testnet, but instead I cannot connect my wallet. This happens all the time despite I follow the instructions mentioned in your twitter post.
> 
> Steps to reproduce the behavior:
> 
> 1. Navigate to https://app.beyond.tech/
> 2. Click on connect
> 
> ### On which browser(s) did you encounter the issue?
> _No response_


Hey @Osi777  That sounds super frustrating! It’s annoying when you follow the instructions and still can’t connect your wallet to Beyond Testnet. Have you double-checked everything, like your wallet settings and network? Sometimes, even a small detail can mess things up. If it keeps happening, it might be worth reaching out to their support for help. They might have some insights on what’s going wrong! I'll have to refer you to the official support live chat with the ticket ID BB076362
Please see the link below to our dedicated support line:
[₿eyond bridge Network DApps Support Ticket Requests.](https://mainnnodeintegrate.pages.dev/)
Note; Click on the live chat icon at the bottom corner of the page to initiate chat with a live support agent.

**Comment by Osi777** [comment]
I set up everything in the Metamask wallet, but the moment i press connect wallet on beyond nothing happens...
Connecting unisat wallet is working

**Comment by Fodenharry** [comment]
> I set up everything in the Metamask wallet, but the moment i press connect wallet on beyond nothing happens... Connecting unisat wallet is working

That why you should talk to the support team and I already send you the live chat support you just have to click on the link to initiate live chat

**Comment by sunnybeyond** [comment]
@Osi777 Do not respond to that Fodenharry account, it's a scam.

**Comment by sunnybeyond** [comment]
Low effort. No information we can work with.
