### ISSUE TITLE
I’m unable to connect UniSat wallet . Might be a bug or not working at the moment 

### ISSUE THREAD

**Issue by Timil3yin** [beyond-btc/community#200]
### Contact details

Www.X.com/Oluwatimil3yinn

### What happened?

I’m unable to connect UniSat wallet . Might be a bug or not working at the moment . I used Mises browser 
![IMG_0620](https://github.com/user-attachments/assets/9c2211e4-e341-44ff-8066-89555b9f7f55)

### On which browser(s) did you encounter the issue?

Chrome, Other (please specify)

**Comment by sunnybeyond** [comment]
Not enough info to work with.

**Comment by Timil3yin** [comment]
But I'm still unable to connect my unisat
What to do please
