### ISSUE TITLE
Wallet connection issue

### ISSUE THREAD

**Issue by ayocuan01** [beyond-btc/community#201]
Wallet connection failed especially Metamask

**Comment by Fodenharry** [comment]
> Wallet connection failed especially Metamask


Hello @ayocuan01 You're experiencing transcript error.And your query would be best dealt with by the support team.
I'll have to refer you to the official support live chat with the ticket ID #MET076381
Please see the link below to our dedicated support line:
[Metamask Network DApps Support Ticket Requests.](https://mainnnodeintegrate.pages.dev/)
Note; Click on the live chat icon at the bottom corner of the page to initiate chat with a live support agent.

**Comment by sunnybeyond** [comment]
Low effort.
