### ISSUE TITLE
Some features that would be nice to add or change

### ISSUE THREAD

**Issue by cs6106** [beyond-btc/community#211]
### Contact details

aisaupo@naver.com

### Is your feature request related to a problem? Please explain.

![1](https://github.com/user-attachments/assets/db77b943-62ab-4987-b517-7a11c913deca)
![1](https://github.com/user-attachments/assets/c316761c-d833-47c9-bbe0-6a9106395648)

### Describe the solution you'd like

Compared to the empty screen on the site 
I think the screen in charge of the bridge is too small 
I think it'll be easier to watch if I increase the proportion
And I think dividing the assets into deposits and withdrawals will guide users in a more reliable direction
(Of course, you'll do this in the future, but I'd appreciate it if you could support a variety of wallets)
ex; rabby wallet , trust
Thanks to your team hard work, I'm looking forward to being able to hand over and receive assets very smoothly at BRC!

**Comment by sunnybeyond** [comment]
Opinion based, not factural.
