### ISSUE TITLE
Suggestions for Enhancement

### ISSUE THREAD

**Issue by Zinocean** [beyond-btc/community#217]
### Contact details

Zinocean@gmail.com

### Is your feature request related to a problem? Please explain.

Based on my review of the testnet, ! recommend the following improvements:
Issue 1: Ambiguous Transaction
Information
To avoid confusion, I suggest displaying the transaction amount alongside the recipient's BTC address, ensuring clarity across various BTC ecosystems (e.g., Runes Taproot, Bitcoin Core).
Issue 2: Limited Transaction Visibility
I propose implementing a comprehensive transaction history feature, allowing users to easily track and view the results of their transactions.

### Describe the solution you'd like

Recommended Solutions
1. Add the transaction amount to the recipient's BTC address.
2. Develop a transaction history feature for users to track transaction statuses and outcomes.

**Comment by sunnybeyond** [comment]
Both are already implemented.
