### ISSUE TITLE
[When I interact with the ₿eyond bridge...]: I Had issues with connecting my metamask but thats for evm 

### ISSUE THREAD

**Issue by Neontoshi** [beyond-btc/community#221]
### What happened?

I was expecting a smooth connection, but instead it did not happened!

i noticed this error only when i am using my laptop when i switch to my phone connections were seamless 
i also had issues navigating i did not know the guide to using the testnet i mean the UI is great but what is a great UI if i cant use the facilities 

i suggest a guide on how to use the testnet and also work on the connection bug NOTE this only happens on Metamask

**Comment by sunnybeyond** [comment]
Low effort. What error?
