### ISSUE TITLE
POSITIVE FEEDBACKS/BUGS/SUGGESTIONS 

### ISSUE THREAD

**Issue by BishopOla** [beyond-btc/community#226]
### Contact details

owokadeolaoluwaoladipupo@gmail.com

### What happened?

Firstly I want to appreciate the team for what they are building, I personally I have been looking for a way to bridge my Eth directly to BTC.
I will say this is a breakthrough in the web3 space.

Positive feedback - Bridging from Eth to BNB to BTC was smooth and fast, I had no issue with that.
Also the UI/UX is easy, good looking, I had a great and satisfied experience.

BUGS: 
1) The site didn't connect to metamask immediately, I had to try multiple times and it worked and I never experienced that after.
2) the site didn't bring approve immediately after imputing my bitcoin testnet address instead of connecting. I had to wait few seconds and it worked.
3)I had issues bringing from tBtc to Eth and BNB despite having 0.000147 tBtc, the site didn't show my balance but rather showing 0 tbc.

SUGGESTIONS:
In working towards the mainnet, I suggest the gas fee to be very low, so that it will be easily accessible by different classes of web3 users

Also the minimum brigde from Eth to BTC should be low, let's say around $10 or lower.

Thank you for building such an amazing Site.
It's BEYOND expectations 

![20241020_104700](https://github.com/user-attachments/assets/15c6bd49-0236-4f2a-9851-78ab03369e97)
![20241020_104707](https://github.com/user-attachments/assets/7b51e82c-cb2e-4546-99b0-064b1fc7cc1c)
![20241020_104717](https://github.com/user-attachments/assets/8f2314c1-8a38-4e05-bb51-e93b3896ffd8)
![IMG-20241020-WA0018](https://github.com/user-attachments/assets/09430d71-4ce1-4f08-b477-3aac4ddeee6c)
![IMG-20241020-WA0017](https://github.com/user-attachments/assets/f787bf9c-a4f8-419d-ac8e-143810aea8f8)
![IMG-20241020-WA0019](https://github.com/user-attachments/assets/93492fc2-4f36-487f-9890-45acffbfc40e)
![IMG-20241020-WA0020](https://github.com/user-attachments/assets/59e47fe3-d11a-4ea8-bc9b-cf2d49d771c4)
![IMG-20241020-WA0021](https://github.com/user-attachments/assets/e772db8c-4234-4c9e-9ffe-da26c3d12523)
![IMG-20241020-WA0026](https://github.com/user-attachments/assets/905b2048-3908-4268-aed6-af44954d16b3)
![IMG-20241020-WA0025](https://github.com/user-attachments/assets/21d79665-0573-45d9-80c7-f4ab6206ddc4)
![IMG-20241020-WA0023](https://github.com/user-attachments/assets/855c3387-9d15-4039-a4f7-032aacb04dfd)
![IMG-20241020-WA0024](https://github.com/user-attachments/assets/3793daf2-f12b-4967-89b9-b0fceffd1496)

**Comment by sunnybeyond** [comment]
Not specific enough, also, we can't change the fees of a network i'm afraid. It's outside out control.
