### ISSUE TITLE
Bitcoin Testnet3 gas too high!

### ISSUE THREAD

**Issue by by7zet** [beyond-btc/community#239]
![Screenshot 2024-10-20 210024](https://github.com/user-attachments/assets/c63fcdec-08de-4d73-ad11-fbede6b039a7)
Gas too high sir

I have completed the interaction with all three chains, and they are all smooth!

NICE WORK!!!

**Comment by w3theo** [comment]
adjust it in settings, click on your address (top right) and then the cogwheel icon.
