### ISSUE TITLE
Bitcoin Testnet Token 

### ISSUE THREAD

**Issue by TosinID** [beyond-btc/community#241]
### Contact details

@TChristkid on X

### Is your feature request related to a problem? Please explain.

The team should make provision for an easier way to get Testnet tokens as it was tough for me to get the minimum needed to bridge from Bitcoin to other chains 

### Describe the solution you'd like

There should be a feature to obtain free Testnet tokens on the test phase to enhance testers complete swaps across all chains during the testnet phase

**Comment by TosinID** [comment]
Every other part of the swaps went smoothly and was right with the estimated time.
I only couldn't bridge from Bitcoin network to others.
The images show that I bridged from other chains easily 
![IMG-20241020-WA0064](https://github.com/user-attachments/assets/a1fba940-4ee2-4b31-a563-5d351611fa13)
![IMG-20241020-WA0070](https://github.com/user-attachments/assets/6ceb8976-ebfa-4748-b57c-5da16701d7f9)
![IMG-20241020-WA0069](https://github.com/user-attachments/assets/e6339d2a-c017-4f88-bc11-deb29fefd8d6)
![IMG-20241020-WA0065](https://github.com/user-attachments/assets/dd371b85-0548-48f2-b2b4-57e2c3d60e6b)
![IMG-20241020-WA0067](https://github.com/user-attachments/assets/1865b879-9408-40a3-9038-74fdc1ad1caf)
![IMG-20241020-WA0070](https://github.com/user-attachments/assets/d1051d23-4e42-4522-bc0b-bf40ff10bdce)

**Comment by sunnybeyond** [comment]
Not specific what went wrong. Can't do much with faucets, they are external providers.
