### ISSUE TITLE
Automatic detention of wrong network

### ISSUE THREAD

**Issue by TosinID** [beyond-btc/community#242]
### Contact details

@TChristkid on X

### Is your feature request related to a problem? Please explain.

As always, I was expecting the site the automatically switch the network of my unisat wallet to Bitcoin Testnet but it didn't.
This made me waste time trying to figure out what happened and had to open ticket before I was reminded to switch my network to Bitcoin Testnet in my Unisat wallet.

### Describe the solution you'd like

There should be prompth detention of wrong network connected with Unisat wallet just like it happens when wrong network is connected in Metamask

**Comment by sunnybeyond** [comment]
This is up to the user to be honest. This won't be a problem in the mainnet variant either.

**Comment by TosinID** [comment]
Understood
