### ISSUE TITLE
Overall feedback on the beyond testnet

### ISSUE THREAD

**Issue by tonyolowe** [beyond-btc/community#247]
The user interface is really nice and straightforward easy for users to navigate!
Getting the test tokens were a bit of a hassle especially the btc and bnb test tokens.
Bridging with my evm wallet was good and seamless. The btc bridging was not as easy for me as the evm. It did not tell me to change my network from fractal bitcoin (which it was on before i began the testing) also it was not easy to bridge different chains.

But overall, it was really good and didn't really but me through any major hassle

**Comment by sunnybeyond** [comment]
Not specific enough to create a case with.

**Comment by introvertefa** [comment]
user interface was a bit confusing for me tbh if you could work on that it would be awesome !!
