### ISSUE TITLE
feedback

### ISSUE THREAD

**Issue by Kodark220** [beyond-btc/community#248]
x.com/vintage8080

_No response_

### What happened?

What I am trying to say is I'm experiencing issues connecting my MetaMask wallet to the Beyond platform. Initially, I succeeded, but the connection dropped after bridging from Sepolia to BTC (RUNES). Reconnection attempts failed.

other Issues faced

BNB faucet balance doesn't display on the Beyond homepage.
Unable to bridge Bitcoin to other chains; even after having TBTC in wallet.

To elevate the experience:

Streamline wallet connection and bridging processes.

Enhance user experience with Percentage-based bridging amount selection, adjustable gas fees, slippage control and enhanced responsiveness for seamless wallet connection

### On which browser(s) did you encounter the issue?

Chrome

**Comment by sunnybeyond** [comment]
Not specific enough to create a case with. Lacking detailed info.
