### ISSUE TITLE
The amount displayed is incorrect and has been delayed for 1 day

### ISSUE THREAD

**Issue by moonsaek** [beyond-btc/community#249]
### Contact details

moonsaek3@gmail.com

### What happened?

The amount shown is wrong and delayed for 1 day, but I have received in the wallet the amount received is 0.1 bwth in brc20[5-byte], and in rune 0.1 weth, hope it helps the team to solve it, good luck

![IMG_20241020_222152](https://github.com/user-attachments/assets/cbfdc300-86f8-43c3-bc5d-c1ea203216e8)
![IMG_20241020_222324](https://github.com/user-attachments/assets/460eeafe-b48c-46fe-a65a-331357bd619b)
![IMG_20241020_222403](https://github.com/user-attachments/assets/feab3edc-da7d-41bd-89f8-ddaf8351d90d)

### On which browser(s) did you encounter the issue?

Other (please specify)

**Comment by sunnybeyond** [comment]
Not specific enough to create a case with. Lacking detailed info.
