### ISSUE TITLE
DARK MODE IMPLEMENTATION

### ISSUE THREAD

**Issue by sirjazzyy** [beyond-btc/community#258]
### Contact details

greatjohnjazzy20@gmail.com

### Is your feature request related to a problem? Please explain.

I am really a fan of dark mode features especially when using an interface or an decentralized Application. So I often try to switch from normal/light to a darker mode which suits my style. 
So while testing the dapp, I couldn't find this feature and it made a little worried as I really love interacting with a darker mode features.

### Describe the solution you'd like

I would suggest the dark mode be implemented as most people prefer it to the lighter mode because of how cool it looks and it doesn't irritate the eye as opposed the lighter version.
Since the logo of beyond as black colour within it and this could be implemented in the ui/ux to make it a lovely experience overall for all users, thanks.

**Comment by sunnybeyond** [comment]
Low effort, lacks details.

**Comment by sirjazzyy** [comment]
Lack details 😂?
You are hilarious

Will you implement dark mode or not?
Stop acting as if you didn't get the message. All the best man
