### ISSUE TITLE
The balance cannot be displayed normally in  test network

### ISSUE THREAD

**Issue by cmjaccount** [beyond-btc/community#263]
### Contact details

https://x.com/rosimajr

### What happened?

After selecting this test network, the interface shows that my balance is 0, but after clicking on the test network selection tab, I can see my balance. Below is a screenshot of mine. I hope it can be displayed on the swap page.
<img width="580" alt="截屏2024-10-21 10 05 48" src="https://github.com/user-attachments/assets/a44c68d0-cd9d-495d-b200-31321579669d">
<img width="529" alt="截屏2024-10-21 10 05 53" src="https://github.com/user-attachments/assets/a7225194-10c2-43f4-9ea5-52808b5454ac">
<img width="358" alt="截屏2024-10-21 10 05 59" src="https://github.com/user-attachments/assets/ddb482b2-9c8e-4d1b-9954-09530304c07c">

### On which browser(s) did you encounter the issue?

Chrome

**Comment by w3theo** [comment]
? its the input, you need to type there how much u want to send, not your balance
