### ISSUE TITLE
Applaud the team for a job well done so far 

### ISSUE THREAD

**Issue by Simbayo** [beyond-btc/community#266]
I shilled thus to my community members awhile back , although some have encountered a little to no issue as not eventing would be perfect , but team made sure they did a very good job on this 
Can’t wait to see the growth of the team and what’s coming , it’s about time we all became a part of something as great as this 
Good work team , keep killin it beyond haha.

**Comment by sunnybeyond** [comment]
Not the quality of feedback we would like to see.
