### ISSUE TITLE
123

### ISSUE THREAD

**Issue by theipuvirchi0b** [beyond-btc/community#275]
Bridging from EVM networks to Bitcoin Testnet generally worked well, but sometimes I encountered problems when the bridge button was inactive or the balance of test tokens in the network was not displayed. Transfers between EVM networks were smooth, with no problems after several attempts. However, the bridge does not include the ability to transfer BRC-20 or Runes tokens, which was disappointing. Another area for improvement is the display of the bridge's expected commission. While the commission is eventually displayed in the wallet when signing a transaction, it should be visible immediately in the interface. I hope that these issues, especially with transfers on the Bitcoin Testnet network, will be addressed in future updates.

**Comment by sunnybeyond** [comment]
Suspect bot or low effort.
