### ISSUE TITLE
BUG

### ISSUE THREAD

**Issue by DrLazier** [beyond-btc/community#282]
### What happened?

The  BTC swap did not go through. Every every other swap went smoothly on my end, no issue what so ever.
![2024-10-21_11-49-41](https://github.com/user-attachments/assets/13a0aa28-a2dd-48af-8905-817a2be56a01)
![2024-10-21_11-58-57](https://github.com/user-attachments/assets/c1154061-5ae6-4dc6-906f-15a5f719c0f7)

**Comment by sunnybeyond** [comment]
Suspect bot or low effort.
