### ISSUE TITLE
METAMASK CONNCETION ISSUE

### ISSUE THREAD

**Issue by Ezeanichimaobi** [beyond-btc/community#287]
### Contact details

Ezeani2256daniel@gmail.com

### What happened?

I was expecting a prompt notification connection on my metamask extension, but instead a qr code appears 

1. Navigate to 'metamask'
2. Click on 'mobile connect'
3. Scan the qr code with your metamask app installed on your mobile device
thats how i dealt with the wallet connect issue

.

### On which browser(s) did you encounter the issue?

Chrome, Metamask, Brave

**Comment by sunnybeyond** [comment]
Suspect bot or low effort.
