### ISSUE TITLE
undefined variables

### ISSUE THREAD

**Issue by zeltron007** [beyond-btc/community#289]
### Contact details

https://x.com/Zeltronx_eth

### What happened?

I was expecting X, but instead Y happened!

1. Navigate to '...'
2. Click on '...'
3. Scroll down to '...'
4. Observe the error / unexpected behavior

implement input validation and sanitization 

### On which browser(s) did you encounter the issue?

Chrome

**Comment by sunnybeyond** [comment]
Suspect bot or low effort.
