### ISSUE TITLE
My feedback from testing Beyond testnet 

### ISSUE THREAD

**Issue by BigSamNFT21** [beyond-btc/community#292]
### Contact details

psalmcrypto192@gmail.com

### What happened?

This are some of the things i noticed  when testing your product.

This site was a pretty good one and very seamless and easy to navigate , the bridging from one protocol to another was a also a smooth experience . i had no issues with that. 

The user interface was very easy to navigate kudos to the team for that .

This are some of the negative things i experienced .

1. Testnet tokens taken time to load at my end  , it was not really fast enough for me .
2.  The site takes too long to connect to my Metamask extension took a while before it work .
3.  And also transaction not really going through even when i had enough gas fee .

**Comment by sunnybeyond** [comment]
Suspect bot or low effort.
