### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by ingranatwaqt** [beyond-btc/community#293]
### Contact details

osmasucshiie@hotmail.com

### What happened?

Connection Issues with EVM MetaMask Wallet
Upon initiating the Testnet, I attempted to connect my EVM MetaMask wallet . However, I encountered an unexpected issue:
1.⁠ ⁠Conflicting Wallet Connection: The platform persistently attempted to connect to my OKX wallet instead of MetaMask, necessitating removal of the OKX wallet to establish a successful connection.
Asset Display Inconsistencies
Despite resolving the connection issue, I observed:
1.⁠ ⁠Incorrect Asset Amounts: The displayed asset amounts remained inaccurate, irrespective of the active wallet.
User Experience Enhancements
To further refine the platform, I suggest:
1.⁠ ⁠Streamlined Transaction Flow: After completing a transaction, I recommend reloading the same page to facilitate additional asset bridging, rather than redirecting to a new webpage.
2.⁠ ⁠Mobile Compatibility: Implementing mobile support would significantly enhance accessibility and user convenience.
Recommended Solutions
To address these challenges, consider:
⁠Enhancing wallet connection logic to prevent conflicts.
⁠Implementing accurate asset amount displays.
⁠Optimizing transaction flow for seamless asset bridging.
Developing mobile-compatible functionality.

**Comment by sunnybeyond** [comment]
Suspect bot or low effort.
