### ISSUE TITLE
1

### ISSUE THREAD

**Issue by tempmerlurafc** [beyond-btc/community#294]
### Contact details

dispprindepo1x@outlook.com

### Describe the solution you'd like

There's a lack of showing your current balance in the swap menu for different networks.
In many bridges or DEXs, this function is lacking. It greatly simplifies understanding the amount you can use for exchanges

Describe the solution you'd like
I’ve added an image above showing how I would like this to look. I frequently use various bridges in the EVM environment, and every time, I miss this feature in different bridges. I hope this is helpful

**Comment by sunnybeyond** [comment]
Suspect bot or low effort.
