### ISSUE TITLE
feedback

### ISSUE THREAD

**Issue by tavulneupok6** [beyond-btc/community#295]
Hi Beyond!
I tested everything, and its good. Cool design
Below I will write a little of my opinion about what I noticed
I would add different network faucet link to the website front page so as to make it easier for testnet user to get test token
I would change the font or used with a bold font, as on other your resources, such as faucet or blog sites
If you can add when connecting a wallet with another network, allow the Metamask to substitute the desired and asking the user about switching. I saw it for more than once
I really liked the beep sound in the transaction confirmation window

**Comment by sunnybeyond** [comment]
Suspect bot or low effort.
