### ISSUE TITLE
BTC BRC 20 to Runes Bridge Transfer Delay

### ISSUE THREAD

**Issue by Jessyxeth** [beyond-btc/community#298]
### Contact details

jessokwuchukwu@gmail.com

### What happened?

I was expecting the bridge from BRC 20 to Runes to take only a few seconds or mins instead it took a lot of time. And at times it says failure to bridge the tokens.
![IMG_7473](https://github.com/user-attachments/assets/cc386282-3074-45fd-85e3-85e1e7e6d137)

1. Navigate to http://app.beyond.tech/
2. Click on connect wallet
3. Scroll down to BTC BRC 20 up, and Runes down, then click on bridge.
4. Observe the error / unexpected behavior

I have attached a screenshot to illustrate the issue.
![IMG_7472](https://github.com/user-attachments/assets/8bb64e23-756a-407f-b16a-fe5778c41d56)
[](url)

### On which browser(s) did you encounter the issue?

Chrome

**Comment by Sarahlouiseryan** [comment]
@Jessyxeth The occasional failure to bridge tokens could be due to network congestion, technical issues, or compatibility problems between the platforms. You might want to check if there are any ongoing technical issues or maintenance with the bridge service.

**Comment by Dappsnode** [comment]
@Jessyxeth If it's taking too long and sometimes failing, it might be worth checking if there are any network issues or if the platform is undergoing maintenance.

**Comment by sunnybeyond** [comment]
Suspect bot or low effort.
