### ISSUE TITLE
[When I interact with the ₿eyond bridge...]: METAMASK connection issues. No real transaction history, and please could you add "max" to the interface to make things easier 

### ISSUE THREAD

**Issue by punnySomto** [beyond-btc/community#303]
### Contact details

beyonder@PunnySomto

### What happened?

I was expecting X, but instead Y happened!

1. Navigate to '...'
2. Click on '...'
3. Scroll down to '...'
4. Observe the error / unexpected behavior

I have attached a screenshot to illustrate the issue.

### On which browser(s) did you encounter the issue?

Chrome

**Comment by sunnybeyond** [comment]
Low effort.
