### ISSUE TITLE
WALLET CONNECTION ON MOBILE DEVICE and ESTIMATED TIME FOR TXN

### ISSUE THREAD

**Issue by Bigman3th** [beyond-btc/community#320]
### Contact details

X.com/Bigman3th 

### What happened?

First off, my Xverse wallet isn’t connecting after my MetaMask wallet did. I think that needs to be fixed then I also think the bridge site needs to be IOS friendly too, it seems a little difficult with an iPhone 
Then lastly the estimated for txn, can it be shorter? Cause personally I think 15mins is a lot to bridge tokens although it’s quite understandable that we’re bridging from a wide range of different chains 
But can the estimated time be shorter than that to make transactions faster 

### On which browser(s) did you encounter the issue?

Metamask, Safari

**Comment by sunnybeyond** [comment]
We can't change how network work.
