### ISSUE TITLE
Everything working smoothly for now 

### ISSUE THREAD

**Issue by Edehjoyce** [beyond-btc/community#321]
### Contact details

joyedeh26@gmail.com

### What happened?

I was expecting X, but instead Y happened!

1. Navigate to '...'
2. Click on '...'
3. Scroll down to '...'
4. Observe the error / unexpected behavior

I have attached a screenshot to illustrate the issue.

### On which browser(s) did you encounter the issue?

Chrome

**Comment by sunnybeyond** [comment]
Low effort.
