### ISSUE TITLE
[Enhance the ₿eyond UI with...]:  swap from EVM networks

### ISSUE THREAD

**Issue by piolicisowt** [beyond-btc/community#324]
### Contact details

pravoril_ri19@hotmail.com

### Is your feature request related to a problem? Please explain.

Good afternoon, I want to report that the swap from EVM networks to the bitcoin network does not work, I really wanted to test this particular function, but for some reason the transfer button just lights up in gray and I can't do anything about it. But in general, your site works without any complaints,
![image](https://github.com/user-attachments/assets/3edc04af-eb0a-4983-b3b3-9955479cf68f)

### Describe the solution you'd like

has made all possible translations and has not noticed any errors! Congratulations, you've done a great job, there's just a little bit left to make it perfect!!!!

**Comment by sunnybeyond** [comment]
Low effort.
