### ISSUE TITLE
[Enhance the ₿eyond UI with...]: new feature

### ISSUE THREAD

**Issue by tiococperta1n** [beyond-btc/community#325]
### Contact details

scepmeropugx@outlook.com

### Is your feature request related to a problem? Please explain.

So far, there isn’t much to say about your new feature, as there are only a couple of networks available for testing swaps, but the potential is immense. As I see it, if all the projects that require depositing coins into a pool integrate your site, and we as users could transfer coins from Ethereum to Bitcoin, I would personally be amazed by the convenience.
![image](https://github.com/user-attachments/assets/6d5f5da2-1fc7-44ac-9342-500eaa099613)

### Describe the solution you'd like

I’m looking forward to your mainnet launch and the first integration with an exciting project! I’m keeping an eye on you! 😉

**Comment by sunnybeyond** [comment]
Low effort.
