### ISSUE TITLE
[Enhance the ₿eyond UI with...]: you could implement a simple FAQ or tutorial 

### ISSUE THREAD

**Issue by taterhypur6** [beyond-btc/community#326]
### Contact details

diaispuya0m@outlook.com

### Is your feature request related to a problem? Please explain.

Hey team! Your project looks promising, but it’s hard to really judge it without more test networks available. It would be super helpful if you could add a section with guides for beginners. Also, having approximate fees when selecting a network would be great.
![image](https://github.com/user-attachments/assets/452a21d9-c073-495d-a9d5-a085a6ed01ca)

### Describe the solution you'd like

Maybe you could implement a simple FAQ or tutorial section that addresses common questions and shows how to calculate fees. I’m looking forward to when the testnet is available so I can try out all the features!

**Comment by sunnybeyond** [comment]
Suspect bot or low effort.
