### ISSUE TITLE
[Enhance the ₿eyond UI with...]: If you can make swapping without using exchanges

### ISSUE THREAD

**Issue by subssenmaumuy4** [beyond-btc/community#327]
### Contact details

malderi_no35@hotmail.com

### Is your feature request related to a problem? Please explain.

Hi Beyond Swap team! I really like your idea of connecting different cryptocurrencies. If you can make swapping without using exchanges work, that would be amazing! But I think it would help a lot if you could show a total balance and info about tokens in different networks.
![image](https://github.com/user-attachments/assets/698ff8f4-7f14-4e89-92e0-54d645954e97)

### Describe the solution you'd like

Perhaps you could integrate a dashboard feature that displays users’ total balances across supported networks. Can’t wait for your mainnet launch!

**Comment by sunnybeyond** [comment]
Suspect bot or low effort.
