### ISSUE TITLE
[Enhance the ₿eyond UI with...]: allow sending tokens to different addresses

### ISSUE THREAD

**Issue by trucimicshihb** [beyond-btc/community#328]
### Contact details

cemecaop8@outlook.com

### Is your feature request related to a problem? Please explain.

Hello! I checked out your site and it seems cool. But I really hope you can allow sending tokens to different addresses. That would be super convenient, especially for businesses. You might want to consider adding an option for users to enter any wallet address for token transfers, not just their own.
![image](https://github.com/user-attachments/assets/f1ecb572-91ad-4506-b5e8-223496474fe6)

### Describe the solution you'd like

I’m looking forward to seeing more developments in the project, including partnerships with other projects and a full testnet. Good luck!

**Comment by sunnybeyond** [comment]
Suspect bot or low effort.
