### ISSUE TITLE
[Enhance the ₿eyond UI with...]: ETH token I want to swap into the bitcoin network "runes"

### ISSUE THREAD

**Issue by detireriar** [beyond-btc/community#329]
### Contact details

gnosisabpuqt@outlook.com

### Is your feature request related to a problem? Please explain.

I started testing your swap, everything works except the bitcoin network, and to be honest, I don't quite understand what the swap is going on, because it says that from the ether network of the ETH token I want to swap into the bitcoin network "runes" what it is and how it looks like, I couldn't figure it out, and it didn't give me a swap. 
![image](https://github.com/user-attachments/assets/be10de6d-c713-47d2-91bb-7c37b23e348d)

### Describe the solution you'd like

You need to add information about what the user gets in the end with such an action and what to do next with this rune, how to turn it into bitcoin!

**Comment by sunnybeyond** [comment]
Suspect bot or low effort.
