### ISSUE TITLE
[Enhance the ₿eyond UI with...]: I wanted to read the tutorial

### ISSUE THREAD

**Issue by reguipuzamt** [beyond-btc/community#330]
### Contact details

handrisan2bu@hotmail.com

### Is your feature request related to a problem? Please explain.

To be honest, everything that is already available on the site is more than enough for average users. I wanted to read the tutorial, but you haven't added it yet. It’s important that it’s clear and answers all possible questions that beginners might have. 
![image](https://github.com/user-attachments/assets/7eca81fd-e0eb-4f40-9411-bb684b16a2a0)

### Describe the solution you'd like

 I’m looking forward to a full testnet with all the networks that are currently unavailable; everything is working great so far.

**Comment by sunnybeyond** [comment]
Suspect bot or low effort.
