### ISSUE TITLE
Site isn't secure

### ISSUE THREAD

**Issue by TayoRichard** [beyond-btc/community#334]
### Contact details

@richardsthayor@gmail.com

### What happened?

I was expecting the site to open when i clicked on the link, but instead i'm seeing site isn't secure.

1. Install Secure Sockets Layer (SSL) Certificate.
2. Ensure That Internal and External Links Use HTTPS.
3. Verify Your Website in Google Search Console.
4. Ensure That HTTP URLs Are Redirected.
5. Update XML Sitemap.

I have attached a screenshot to illustrate the issue.
<img width="1503" alt="Screenshot 2024-10-23 at 05 06 49" src="https://github.com/user-attachments/assets/b24796f4-a47f-457e-8718-ba6d473c59a4">

### On which browser(s) did you encounter the issue?

Chrome

**Comment by sunnybeyond** [comment]
Browser issue on your end. Can't reproduce.
