### ISSUE TITLE
Balance display problem

### ISSUE THREAD

**Issue by xianghuolvyou** [beyond-btc/community#336]
### Contact details

https://x.com/PapadaanCloth

### What happened?

<img width="357" alt="截屏2024-10-21 10 12 08" src="https://github.com/user-attachments/assets/b1b6cb21-fc7b-4c87-acba-f17583f46fd0">
The address being displayed cross-chain. The btc display address is the same as the eth address, but the actual btc address is different.

### On which browser(s) did you encounter the issue?

Chrome

**Comment by sunnybeyond** [comment]
Is a placeholder.
