### ISSUE TITLE
Provide the contract address for each available token, as there are many improvements needed.

### ISSUE THREAD

**Issue by sanzjago** [beyond-btc/community#338]
Add a faucet link on the BeyondBTC homepage. Several improvements are necessary, such as the overly simplistic UI/UX, many bugs like analytics turning into a blank white screen when clicked, and the inability to perform cross-chain transactions. There is still no route to BTC Runes and BRC20. The absence of a dedicated explorer makes it difficult for users to understand the existing routes. Audits are also lacking, with no code or GitHub available.

Most importantly, provide the faucet link and documentation explaining the bridge route and the available token contract addresses.

**Comment by sunnybeyond** [comment]
Duplicate
