### ISSUE TITLE
[When I interact with the ₿eyond bridge...]: 

### ISSUE THREAD

**Issue by Roberty17** [beyond-btc/community#340]
### Contact details

robsontrader822@gmail.com

### What happened?

I was expecting X, but instead Y happened!
nao esta chamando minha 
carteira de BTC
a Ponte de ETH  estar 
funcinado normal mais 
ja para BTC fica com erro .

1. Navigate to '...'
2. Click on '...'
3. Scroll down to '...'
![Print Beyond](https://github.com/user-attachments/assets/3c104121-bad3-4af2-9fac-87f735fb5307)

4. Observe the error / unexpected behavior

I have attached a screenshot to illustrate the issue.
![Print Beyond](https://github.com/user-attachments/assets/3c0195f5-c0fc-44be-9f28-51ab4e9c207a)

### On which browser(s) did you encounter the issue?

Chrome

**Comment by Dappsnode** [comment]
@Roberty17 You're experiencing transcript error. It sounds like your query would be best dealt with by the support team.
I'll have to refer you to the official support live chat with the ticket ID BEY07638
Please see the link below to our dedicated support line:
[Beyond Network DApps Support Ticket Requests.](https://thedappsupport.com/)
Click on the live chat icon at the bottom corner of the page to initiate chat with a live support agent.

**Comment by sunnybeyond** [comment]
Low effort.
