### ISSUE TITLE
Try all the features in beyond

### ISSUE THREAD

**Issue by Paullumere** [beyond-btc/community#341]
**Today i done try all future on [Beyond Tech](https://app.beyond.tech).**

what experience did I get?? 

![IMG_20241022_214721](https://github.com/user-attachments/assets/c03e62fc-5e4d-4b03-97ab-baab18d590c0)

All procces bridge i not get problem, i love you platfrom the UI is so much.
I have circled something wrong in the placement of the logo only, hope always succes you build on bitcoin fam.

can't wait mainet ongoing

**Comment by sunnybeyond** [comment]
Low effort.
