### ISSUE TITLE
Insufficient funds

### ISSUE THREAD

**Issue by eleetmo** [beyond-btc/community#343]
### Contact details

x.com/eleetsol

### What happened?

I'm trying to bridge from BTC testnet to Sepolia but it keeps saying Insufficient Funds when i have testnet BTC in the wal let.

![image](https://github.com/user-attachments/assets/3ff490fd-4823-46cf-8fb2-4a05c8cd8fbc)

**Comment by sunnybeyond** [comment]
Not enough funds.
