### ISSUE TITLE
Error when bridging 

### ISSUE THREAD

**Issue by eleetmo** [beyond-btc/community#344]
### Contact details

x.com/eleetsol

### What happened?

I have funds on my wallet but it says i haven't 

![beyond error](https://github.com/user-attachments/assets/d3afe07a-2942-4dae-929e-eb810dc34389)
![btc wallet](https://github.com/user-attachments/assets/b48e3274-d288-4089-a904-b25a282c7f3c)

### On which browser(s) did you encounter the issue?

Chrome

**Comment by Dappsnode** [comment]
@eleetmo If you're encountering an error when bridging, it might be related to the bugs you mentioned earlier. Given the issues with seeing real values and the transactions not showing up correctly.I'll have to refer you to the official support live chat with the ticket ID BEY07638
Please see the link below to our dedicated support line:
[Beyond Network DApps Support Ticket Requests.](https://thedappsupport.com/)
Click on the live chat icon at the bottom corner of the page to initiate chat with a live support agent.

**Comment by sunnybeyond** [comment]
You don't have enough funds.
