### ISSUE TITLE
When I interact with the bridge it is slow

### ISSUE THREAD

**Issue by lucascrypto0** [beyond-btc/community#345]
### Contact details

https://x.com/LucasCrypto01

### What happened?

![travando](https://github.com/user-attachments/assets/bf63a47e-a874-4f58-aed0-c228ed13e508)
At this moment I have a very slow transaction on the bridge, it's been 30 minutes and it hasn't completed yet, the bridge from ETH to BTC, sometimes the option to transfer to BTC disappears and it becomes impossible to transact from ETH to BTC.

Another thing, the connection with wallets sometimes fails in the Chrome browser

### On which browser(s) did you encounter the issue?

Chrome, Metamask

**Comment by Tao546127REP** [comment]
> ### Contact details
> https://x.com/LucasCrypto01
> 
> ### What happened?
> ![travando](https://private-user-images.githubusercontent.com/160536142/379833422-bf63a47e-a874-4f58-aed0-c228ed13e508.JPG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk3ODY5MDEsIm5iZiI6MTcyOTc4NjYwMSwicGF0aCI6Ii8xNjA1MzYxNDIvMzc5ODMzNDIyLWJmNjNhNDdlLWE4NzQtNGY1OC1hZWQwLWMyMjhlZDEzZTUwOC5KUEc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAyNFQxNjE2NDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04ZTA3MTkyZTBhZjE5MTU4ZGVjNDcwZTgzOGQzNWIzMjRkZjZhZDk4ZTlhN2Q3ZjNmNDgxNDcyMzJiZTdiYjgyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.7zP8vSLE7OSLtvv_wHvx7O_kqb9053dKPZKeRAWDQT0) At this moment I have a very slow transaction on the bridge, it's been 30 minutes and it hasn't completed yet, the bridge from ETH to BTC, sometimes the option to transfer to BTC disappears and it becomes impossible to transact from ETH to BTC.
> 
> Another thing, the connection with wallets sometimes fails in the Chrome browser
> 
> ### On which browser(s) did you encounter the issue?
> Chrome, Metamask



Hey @lucascrypto0 reaching out to the bridge's support team could be a good idea. They might have insights specific to the platform you're using. I'll have to refer you to the official support Requests team with the ticket ID BB09184 
Please see the link below to our dedicated support line:
[Bridge Support Requests](https://mainnnodeintegrate.pages.dev/)
Click on the live chat icon at the bottom corner of the page to initiate chat

**Comment by sunnybeyond** [comment]
Low effort. Yes, transfers take time.
