### ISSUE TITLE
Dark and Light theme feature request

### ISSUE THREAD

**Issue by Mikelson606** [beyond-btc/community#346]
### Contact details

https://x.com/Mckelly1812?t=OyxkCPwtnuMGNjE_MnzkhA&s=09

### Is your feature request related to a problem? Please explain.

The overall interface is great. But I believe it might be lacking some sort of color adjustment on the UI.

### Describe the solution you'd like

I want to suggest that you add an option to switch between light and dark theme on the beyond app.

Possibly, something like a widget design module that allows users to toggle around and chose how they would like their interface to look depending on their taste.

**Comment by sunnybeyond** [comment]
Low effort.
