### ISSUE TITLE
Can not complete the Bridge

### ISSUE THREAD

**Issue by by7zet** [beyond-btc/community#347]
### What happened?

I was expecting the bridge would be completed smoothly, but But 4 days have passed and it is still pending
My EVM address is 0x8f0444bffda6c2af087403f47da4a32c20acb422

I have attached a screenshot to illustrate the issue.
![Screenshot 2024-10-25 004950](https://github.com/user-attachments/assets/0614afea-3948-421e-954b-1e9a77952fc9)
![Screenshot 2024-10-25 004205](https://github.com/user-attachments/assets/79834eb2-35fd-4c36-b5ea-dc7d6dcb5777)

**Comment by sunnybeyond** [comment]
Low effort.
