### ISSUE TITLE
Unable to cross chain from SpeoliaETH to Bitcoin Testnet in ₿ridge bridge

### ISSUE THREAD

**Issue by HIKJLJB** [beyond-btc/community#35]
### Contact details

hikjljb@gmail.com

### What happened?

I was expecting a chain from SpeoliaETH to Bitcoin testnet on the ₿ridge bridge, but couldn't click confirm to start

1. Navigate to brigde page
2. Select SpeoliaETH above -ETH below and select Bitcoin Testnet
3. brigde cannot be clicked (tried to switch tokens)
![20cf56631b55e542d32a19cdd5af1c0](https://github.com/user-attachments/assets/7a30a095-7148-4902-b0bb-31b0e2a4ed88)

### On which browser(s) did you encounter the issue?

Chrome

**Comment by sunnybeyond** [comment]
Probably didn't select testnet in BTC wallet. Is not a testnet address as recipient.

**Comment by HIKJLJB** [comment]
I'm sure it's the BTC test network address, And the test net link is
selected

Sunny | Beyond ***@***.***> 于 2024年10月20日周日 20:32写道：
