### ISSUE TITLE
Can't use the bridge from Sepolia ETH to BTC testnet

### ISSUE THREAD

**Issue by eleetmo** [beyond-btc/community#352]
### Contact details

x.com/eleetsol

### What happened?

Was doing more bridges and now i can't bridge from Sepolia to BTC

![image](https://github.com/user-attachments/assets/60af6a1f-d6d7-46a3-ac4b-02e23e1be7d6)

### On which browser(s) did you encounter the issue?

Chrome

**Comment by sunnybeyond** [comment]
Suspect bot or low effort.
