### ISSUE TITLE
[When I interact with the ₿eyond bridge...]: 

### ISSUE THREAD

**Issue by marcussilva1984** [beyond-btc/community#355]
### Contact details

looping infinity

### What happened?

I was expecting X, but instead Y happened!

1. Navigate to '...'
2. Click on '...'
3. Scroll down to '...'
4. Observe the error / unexpected behavior

I have attached a screenshot to illustrate the issue.
![Seleção_002](https://github.com/user-attachments/assets/718624b7-af7b-49fd-8647-ecd09aa8f6f8)

### On which browser(s) did you encounter the issue?

Chrome

**Comment by marcussilva1984** [comment]
I task of 3 times today

**Comment by sunnybeyond** [comment]
Suspect bot or low effort.
