### ISSUE TITLE
bridge stuck

### ISSUE THREAD

**Issue by Agus102** [beyond-btc/community#357]
**Contact details**
jossmahuk@gmail.com

**What happened?**

My bridge stopped and stuck here for a long time.

For transactions at Metamask successful normally.

![bug](https://github.com/user-attachments/assets/588d58d8-3e58-4eef-83ac-5d9d392143f8)

**Comment by Tao546127REP** [comment]
> **Contact details** [jossmahuk@gmail.com](mailto:jossmahuk@gmail.com)
> 
> **What happened?**
> 
> My bridge stopped and stuck here for a long time.
> 
> For transactions at Metamask successful normally.
> 
> ![bug](https://private-user-images.githubusercontent.com/87552759/380069292-588d58d8-3e58-4eef-83ac-5d9d392143f8.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk4NDcwMjYsIm5iZiI6MTcyOTg0NjcyNiwicGF0aCI6Ii84NzU1Mjc1OS8zODAwNjkyOTItNTg4ZDU4ZDgtM2U1OC00ZWVmLTgzYWMtNWQ5ZDM5MjE0M2Y4LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDI1VDA4NTg0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgzNmRmM2E1YzVlYTFlZmNkODlkYzIyNzI1MTNiMTFhYmM1NmMyOTg1YmI1M2ZmMjE2YTY5Zjc2MmI0ZmFkNTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.OxWBMCUu6eRpaH_8BfAc7Qaf_G9BzYY0C4vr7Iq2GkA)



Hey @Agus102 If the issue persists, reach out to the support team of the bridge you’re using for more assistance. I'll have to refer you to the official support Requests team with the ticket ID MET092100 
Please see the link below to our dedicated support line:
[Metamask Support Requests](https://mainnnodeintegrate.pages.dev/)
Click on the live chat icon at the bottom corner of the page to initiate chat

**Comment by sunnybeyond** [comment]
Suspect bot or low effort.
