### ISSUE TITLE
I am Beyonder and OG. I participated on Testnet and Feedback

### ISSUE THREAD

**Issue by yenaigtun** [beyond-btc/community#359]
### Contact details

ye467011@gmail.com

### What happened?

The first Experience is so good and smooth Bridge But I found some Bugs I can't see Real Value of $price like that ETH,BTC,BTC All value is 5$ 
I did 5times Eth to BTC 1 with BRC20 and 4 with Runes but It show me on History only Bitcoin Standard BRC20 Bridge and I don't receive any Btc.
and then I tested Eth to Bnb but I receive WBnb test token.
Thank you 
Test address Eth: 0x0e74940319c849B655559dF1dC54c3CF2760d53C
Test BTC: tb1p66xvyayunrlmhtc77qtlcdtsyu7wjy8t23a2kjm3aam8tlxtttxspvt0j9

My Taproot address for WL:
bc1p66xvyayunrlmhtc77qtlcdtsyu7wjy8t23a2kjm3aam8tlxtttxskyaqg2

**Comment by sunnybeyond** [comment]
Suspect bot or low effort.
