### ISSUE TITLE
feedback

### ISSUE THREAD

**Issue by oluwabdt** [beyond-btc/community#362]
Overall, I had a positive experience with the platform. The user interface is intuitive and easy to navigate. However, acquiring test tokens, particularly for BTC and BNB, was somewhat challenging.
I found bridging with my EVM wallet to be seamless, but bridging BTC required additional steps that weren't clearly indicated, such as switching from the Fractal Bitcoin network. Bridging multiple chains also proved difficult.
Despite these minor hurdles, the platform performed well, and I didn't encounter any significant issues.

**Comment by sunnybeyond** [comment]
Suspect bot or low effort.

**Comment by sunnybeyond** [comment]
Tried to get WL with closed comment. Banned from any further WL possibilities.
