### ISSUE TITLE
[When I interact with the ₿eyond bridge...]: its not as easy to understand especially for new people to the crypto world (like me )

### ISSUE THREAD

**Issue by introvertefa** [beyond-btc/community#363]
### What happened?

I was expecting X, but instead Y happened!

1. Navigate to '...'
2. Click on '...'
3. Scroll down to '...'
4. Observe the error / unexpected behavior

I have attached a screenshot to illustrate the issue.

**Comment by sunnybeyond** [comment]
Suspect bot or low effort.
