### ISSUE TITLE
BEYOND TECH TEST

### ISSUE THREAD

**Issue by ylkelvin** [beyond-btc/community#366]
### What happened?

i loved the ui of the website and it was also very easy to navigate so kudos to the design team. i experienced issues whn trying to bridge from BTC to BTC runes and from ETH to BTC but every ETH to ETH bridge was seemless and quick!

**Comment by Dappsnode** [comment]
@ylkelvin You're experiencing transcript error. It sounds like your query would be best dealt with by the support team.
I'll have to refer you to the official support live chat with the ticket ID BEY07638
Please see the link below to our dedicated support line:
[Beyond BTC Network DApps Support Ticket Requests.](https://thedappsupport.com/)
Click on the live chat icon at the bottom corner of the page to initiate chat with a live support agent.

**Comment by sunnybeyond** [comment]
Suspect bot or low effort.

**Comment by ylkelvin** [comment]
i wasn't whitelisted?
