### ISSUE TITLE
[When I interact with the ₿eyond bridge...]: I interact with Beyond Bridge but the ETH sepolia showing 0

### ISSUE THREAD

**Issue by huokoden** [beyond-btc/community#369]
### Contact details

x.com/hhuo32

### What happened?

I was expecting successful bridge, but instead the ETH sepolia is showing 0 happened!

1. Navigate to https://app.beyond.tech
2. Click on 'ETH on sepolia testnet'
3. Scroll down to 'ETH'

### On which browser(s) did you encounter the issue?

Chrome

**Comment by sunnybeyond** [comment]
Suspect bot or low effort.
