### ISSUE TITLE
Unisat connecting issue

### ISSUE THREAD

**Issue by reeeveeerseee** [beyond-btc/community#37]
### Contact details

https://x.com/reeeveeerseee

### What happened?

Hello, I had an issue with connecting unisat wallet but when i tried few minutes later it was working.
![image](https://github.com/user-attachments/assets/3ff8be35-0d3d-412b-83a9-0df6ea5f0f80)

I used brigde and it was really fast, I like it.

**Comment by sunnybeyond** [comment]
No information we can work with.
