### ISSUE TITLE
Long transaction

### ISSUE THREAD

**Issue by Junaobh09** [beyond-btc/community#370]
### Contact details

@JCrypto10955 - X

### What happened?

Making the bridge between SEPOLIA and BitCointestnet, with RUNEs or BRC20, it is taking a long time to get the site ok. Sometimes the transaction takes days.
![Error1](https://github.com/user-attachments/assets/0c6019ef-c9d7-4651-a2fa-de99b82ff836)

### On which browser(s) did you encounter the issue?

Brave

**Comment by sunnybeyond** [comment]
Suspect bot or low effort.
