### ISSUE TITLE
bug in bridge for btc - BRC-20

### ISSUE THREAD

**Issue by lucascrypto0** [beyond-btc/community#371]
### Contact details

https://x.com/LucasCrypto01

### What happened?

When I try to bridge the Ethereum Sepolia network to the BTC BRC-20 network it simply isn't showing up, I'm putting up an image that shows this.

This has been happening for a while now only for the BTC bridge
![ynwnyw](https://github.com/user-attachments/assets/1c2e31a7-b945-47a2-bc75-e566ed080a72)

### On which browser(s) did you encounter the issue?

Chrome, Metamask

**Comment by sunnybeyond** [comment]
you are trying to bridge to mainnet addy.
