### ISSUE TITLE
bug bridge de sepolia eth fron btc

### ISSUE THREAD

**Issue by fael004** [beyond-btc/community#372]
### Contact details

https://x.com/RafaelH87863684

### What happened?

Hello beyond, I've been trying to bridge from Sepolia ETH to BTC for 3 days. I have a balance in my EVM wallet in Sepolia but it doesn't enable me to bridge.
![Captura de tela 2024-10-25 102204](https://github.com/user-attachments/assets/728f0615-4f24-4d74-b4d9-fa0d0686e31b)

![Captura de tela 2024-10-25 102221](https://github.com/user-attachments/assets/7a194ee4-92df-4822-a217-b8241331bbf7)

**Comment by Dappsnode** [comment]
@fael004f you're having trouble bridging from Sepolia ETH to BTC, It sounds like your query would be best dealt with by the support team.
I'll have to refer you to the official support live chat with the ticket ID BEY07638
Please see the link below to our dedicated support line:
[Beyond Network DApps Support Ticket Requests.](https://thedappsupport.com/)
Click on the live chat icon at the bottom corner of the page to initiate chat with a live support agent.

**Comment by sunnybeyond** [comment]
You tried to swap to mainnet.
