### ISSUE TITLE
When it comes to bridging the gap

### ISSUE THREAD

**Issue by henryguns** [beyond-btc/community#373]
### Contact details

https://twitter.com/leohjlr,  leo21rsrs@gmail.com, discord = leoguns

### What happened?

I was expecting X, but instead Y happened!

1. Navigate to '...'
2. Click on '...'
3. Scroll down to '...'
4. Observe the error / unexpected behavior

I have attached a screenshot to illustrate the issue.
When I go to do the Sepolia Bridge test net, it's taking a long time, to get out of the first part and go to the second part.
![bug beyond](https://github.com/user-attachments/assets/c31d9a22-adce-4bfb-a5af-1e28bc1e1757)

### On which browser(s) did you encounter the issue?

Metamask, Edge

**Comment by sunnybeyond** [comment]
Suspect bot or low effort.
