### ISSUE TITLE
General Feedback and Bug while bridging

### ISSUE THREAD

**Issue by eleetmo** [beyond-btc/community#375]
### Contact details

x.com/eleetsol

### What happened?

I'm testing the bridge for some days now.

While bridging from Sepolia i can't bridge to BTC, the same happens when trying to bridge from BNB to BTC, another bug i keep getting is when trying to bridge from BTC to any chain, i keeps saying i need funds when my wallet have plenty of testnet BTC.

Screenshots attached showing all cases, thanks for the support.

![Beyond 5](https://github.com/user-attachments/assets/08ad74dc-20b9-44f9-87e2-24c939416c5c)
![Beyond 4](https://github.com/user-attachments/assets/69010e91-63a5-4e64-bed0-32281cb65aa6)
![Beyond 3](https://github.com/user-attachments/assets/a0f613e0-4ef2-4dc3-a7ec-931d66e9c1de)
![Beyond 2](https://github.com/user-attachments/assets/ab7937ad-acc6-4118-ad49-0b84ce391aa9)
![Beyond](https://github.com/user-attachments/assets/af13a7da-f721-444a-8856-22346b297207)

### On which browser(s) did you encounter the issue?

Chrome

**Comment by sunnybeyond** [comment]
You are trying to bridge to mainnet instead of testnet.
