### ISSUE TITLE
[When I interact with the ₿eyond bridge...]: 

### ISSUE THREAD

**Issue by tchelocpv** [beyond-btc/community#377]
### Contact details

https://x.com/Marcelo88632936

### What happened?

I was expecting X, but instead Y happened!

1. Navigate to google chrome
2. Click on bridge but it doesn't work I can't exchange sepolia ethereum for bitcoin testnet,  why doesn't it work
![Captura de tela 2024-10-25 104757](https://github.com/user-attachments/assets/640339ff-d78b-4c4d-81e2-14a8bf4a5084)

3. Scroll down until you see the 15 minute countdown, but hours have passed and it won't release
4. Observe the error / unexpected behavior

I have attached a screenshot to illustrate the issue.

### On which browser(s) did you encounter the issue?

Chrome, Metamask

**Comment by tchelocpv** [comment]
GM

**Comment by Tao546127REP** [comment]
> ### Contact details
> https://x.com/Marcelo88632936
> 
> ### What happened?
> I was expecting X, but instead Y happened!
> 
> Steps to reproduce the behavior:
> 
> 1. Navigate to google chrome
> 2. Click on bridge but it doesn't work I can't exchange sepolia ethereum for bitcoin testnet,  why doesn't it work
>    ![Captura de tela 2024-10-25 104757](https://private-user-images.githubusercontent.com/131601431/380192117-640339ff-d78b-4c4d-81e2-14a8bf4a5084.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk4NjU2MjksIm5iZiI6MTcyOTg2NTMyOSwicGF0aCI6Ii8xMzE2MDE0MzEvMzgwMTkyMTE3LTY0MDMzOWZmLWQ3OGItNGM0ZC04MWUyLTE0YThiZjRhNTA4NC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAyNVQxNDA4NDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yOWZlOTJhODFkNzZlMTYxNjI5OGU4NzJlODliZDQyYWU5Y2MzOGM1ZjIxMjQ5NDc1Yzc0YjRhZDJkZTU1ZDMyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.5LTSTEb4ILN6nfJ8aqyf3xAZJG9dpg7E4F4v5Ll6xqU)
> 3. Scroll down until you see the 15 minute countdown, but hours have passed and it won't release
> 4. Observe the error / unexpected behavior
> 
> I have attached a screenshot to illustrate the issue.
> 
> ### On which browser(s) did you encounter the issue?
> Chrome, Metamask



Gm @tchelocpv reaching out to their support team could provide more specific guidance. I'll have to refer you to the official support Requests team with the ticket ID MET052108 
Please see the link below to our dedicated support line:
[Metamask Support Requests](https://mainnnodeintegrate.pages.dev/)
Click on the live chat icon at the bottom corner of the page to initiate chat

**Comment by sunnybeyond** [comment]
Suspect bot or low effort.
