### ISSUE TITLE
[When I interact with the ₿eyond bridge...]: 

### ISSUE THREAD

**Issue by WilliamAlexandrino** [beyond-btc/community#378]
### Contact details

https://x.com/Williaam_Allves

### What happened?

[When I interact with the ₿eyond bridge...]: 

It's giving me an error when connecting my wallet, and it's taking a long time to make the bridge.

### On which browser(s) did you encounter the issue?

Chrome, Metamask

**Comment by Tao546127REP** [comment]
> ### Contact details
> https://x.com/Williaam_Allves
> 
> ### What happened?
> [When I interact with the ₿eyond bridge...]:
> 
> It's giving me an error when connecting my wallet, and it's taking a long time to make the bridge.
> 
> ### On which browser(s) did you encounter the issue?
> Chrome, Metamask



If the bridging process is taking too long, you might want to refresh the page or try reconnecting your wallet. If it continues to be a hassle, reaching out to the support team for the ₿eyond bridge could help clear things up. I'll have to refer you to the official support Requests team with the ticket ID ₿B148210 
Please see the link below to our dedicated support line:
[₿eyond bridge Support Requests](https://mainnnodeintegrate.pages.dev/)
Click on the live chat icon at the bottom corner of the page to initiate chat Hope it gets sorted out soon!

**Comment by sunnybeyond** [comment]
Suspect bot or low effort.
