### ISSUE TITLE
When I interact with the Beyong bridge, the bar that indicates that it is sending does not fill up

### ISSUE THREAD

**Issue by andretoisao336** [beyond-btc/community#379]
### Contact details

https://x.com/andretoisao10

### What happened?

 I go to the Beyond website, enter Sepholia ETH and put it in the BRC20 network just below. When I go to do the Bridge, the sending bar is only a little filled, I wait for the time to pass, which is 15 minutes, and nothing happens.
![Captura de tela 2024-10-25 104836](https://github.com/user-attachments/assets/4e95c837-409f-4fb5-bb0a-70e748b8cb95)

### On which browser(s) did you encounter the issue?

Other (please specify)

**Comment by sunnybeyond** [comment]
Suspect bot or low effort.
