### ISSUE TITLE
[When I interact with the ₿eyond bridge]

### ISSUE THREAD

**Issue by AndreyP55** [beyond-btc/community#38]
### Contact details

https://x.com/AndreyPortnikov

### What happened?

https://x.com/AndreyPortnikov

What happened?
Asset bridge from Sepolia Testnet and BNB Chain Testnet to Bitcoin Testnet does not work. When sending funds from the chain, tokens are approved, but the bridge button is inactive. But sending tokens between Sepolia Testnet and BNB Chain Testnet networks is successful, tokens arrive within 5 minutes from one network to another.

On which browser(s) did you encounter the issue?
Edge

**Comment by Bogdan0112** [comment]
Dude, are you lazy enough to just copy my whole post?
https://github.com/beyond-btc/feedback/issues/17#issue-2594737239

**Comment by w3theo** [comment]
you forgot to copy the screenshot from the original issue

**Comment by sunnybeyond** [comment]
Stolen content.
