### ISSUE TITLE
[When I interact with the ₿eyond bridge...]: 

### ISSUE THREAD

**Issue by epocaboa1** [beyond-btc/community#380]
### Contact details

genildobarrosmae@gmail.com

### What happened?

Very quickly, I'm enjoying my wallet more, sometimes I make mistakes
![erroa](https://github.com/user-attachments/assets/d45cbe54-06dc-4726-a751-e1ba8a575b81)

**Comment by epocaboa1** [comment]
poor performance in google crome and opera

**Comment by sunnybeyond** [comment]
Suspect bot or low effort.
