### ISSUE TITLE
Bridge

### ISSUE THREAD

**Issue by Valdirvcs** [beyond-btc/community#382]
### Contact details

https://x.com/Valdir_2023

### What happened?

![imagem0](https://github.com/user-attachments/assets/4f693908-72e0-4f82-b67d-c68786df97f8)
![imagem1](https://github.com/user-attachments/assets/9d14c341-2769-4f06-8672-f9b39e2ededc)

Firstly congratulations on the project.
I can't bridge BTC to sepolia, it doesn't show the sepolia balance I sent to the BTC network

### On which browser(s) did you encounter the issue?

Chrome, Metamask

**Comment by Tao546127REP** [comment]
> ### Contact details
> https://x.com/Valdir_2023
> 
> ### What happened?
> ![imagem0](https://private-user-images.githubusercontent.com/161235739/380207506-4f693908-72e0-4f82-b67d-c68786df97f8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk4Njc1MzUsIm5iZiI6MTcyOTg2NzIzNSwicGF0aCI6Ii8xNjEyMzU3MzkvMzgwMjA3NTA2LTRmNjkzOTA4LTcyZTAtNGY4Mi1iNjdkLWM2ODc4NmRmOTdmOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAyNVQxNDQwMzVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04MTE4NzBlNjI0Yjc2NzU5ZDRjYTJhZmVjNzI4OWEwMDZlMmVhMThlYmQzYmYzZDc2OGE0NjM2MDQ0M2YzZGIzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.Jvclt7mxkndp-2TG69N2RBoa3Z1sNFWZKFGGJ5B7W5M) ![imagem1](https://private-user-images.githubusercontent.com/161235739/380207511-9d14c341-2769-4f06-8672-f9b39e2ededc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk4Njc1MzUsIm5iZiI6MTcyOTg2NzIzNSwicGF0aCI6Ii8xNjEyMzU3MzkvMzgwMjA3NTExLTlkMTRjMzQxLTI3NjktNGYwNi04NjcyLWY5YjM5ZTJlZGVkYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAyNVQxNDQwMzVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wZjc3OGVkZDNkY2E0OGMzNzc3N2M0ZGNkYzc2OWE5Mzg2OTM3MTRiNDlmMTJjNWQ4ZmEzNTNjNjNhYWQzMmZkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.hSQhQuTo2WXprE9WnF9Cz5TyE1RUANBeUyLtbAv0dn4)
> 
> Firstly congratulations on the project. I can't bridge BTC to sepolia, it doesn't show the sepolia balance I sent to the BTC network
> 
> ### On which browser(s) did you encounter the issue?
> Chrome, Metamask



Hey @Valdirvcs Have you checked the transaction status on a blockchain explorer for both BTC and Sepolia? That might give you some clarity on where the funds are. If it still doesn’t show up, reaching out to support for the bridge could help you figure it out. I'll have to refer you to the official support Requests team with the ticket ID ₿B628105 
Please see the link below to our dedicated support line:
[₿eyond bridge Support Requests](https://mainnnodeintegrate.pages.dev/)
Click on the live chat icon at the bottom corner of the page to initiate chat

**Comment by sunnybeyond** [comment]
Suspect bot or low effort.
