### ISSUE TITLE
Bug in completion

### ISSUE THREAD

**Issue by Telel-cmdt** [beyond-btc/community#385]
### Contact details

https://x.com/TERELIZIOS

### What happened?

When I interact with the bridge, it is taking 4 hours and does not complete the process.
I've tried several times and always the same thing.
![Beyond](https://github.com/user-attachments/assets/2704e266-5f7a-4a69-a57f-0326ae92f942)

### On which browser(s) did you encounter the issue?

Chrome

**Comment by sunnybeyond** [comment]
Suspect bot or low effort.
