### ISSUE TITLE
Delayed bridge on BTC network

### ISSUE THREAD

**Issue by ABNTSOL** [beyond-btc/community#387]
### Contact details

sharkweby@gmail.com or https://x.com/ABNTSOL

### What happened?

Hello everyone, first of all I want to congratulate the team for the project.
Yesterday I had a problem when I tried to create a bridge from the Ethereum network to the BTC network. I tried several times to create the bridge and it gave me an error and it didn't work at all. I finally managed to do it, after almost an hour, but then it was another struggle. It took almost 5 hours to complete the process!
I imagine this is an atypical problem, but I thought it would be interesting to report the problem to the team.

### On which browser(s) did you encounter the issue?

Chrome

**Comment by sunnybeyond** [comment]
Suspect bot or low effort.
