### ISSUE TITLE
[When I interact with the ₿eyond bridge...]: ao interagir com a ponte

### ISSUE THREAD

**Issue by paulo2pva** [beyond-btc/community#388]
### Contact details

https://x.com/pedropa31646081

### What happened?

 when starting the bridge,it calls both wallets at once,i think this gets in the way when setting up a bridge for the ing network. i have 2 transactions that  are more than 2 days old and they have not been completed.

**Comment by sunnybeyond** [comment]
Suspect bot or low effort.
