### ISSUE TITLE
Transaction bug

### ISSUE THREAD

**Issue by Telel-cmdt** [beyond-btc/community#389]
### Contact details

https://x.com/TERELIZIOS

### What happened?

When I interact with the bridge, it is taking a long time (3-4-5 hours) and does not complete.
confirms the transaction in the metamask, but does not complete the transaction in the horizontal bar.
![Beyond-24 10 24](https://github.com/user-attachments/assets/5494e55a-d9f0-4def-87aa-a3a75bfcb4a0)

### On which browser(s) did you encounter the issue?

Chrome

**Comment by Tao546127REP** [comment]
> ### Contact details
> https://x.com/TERELIZIOS
> 
> ### What happened?
> When I interact with the bridge, it is taking a long time (3-4-5 hours) and does not complete. confirms the transaction in the metamask, but does not complete the transaction in the horizontal bar. ![Beyond-24 10 24](https://private-user-images.githubusercontent.com/181602753/380235888-5494e55a-d9f0-4def-87aa-a3a75bfcb4a0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk4ODA2MzAsIm5iZiI6MTcyOTg4MDMzMCwicGF0aCI6Ii8xODE2MDI3NTMvMzgwMjM1ODg4LTU0OTRlNTVhLWQ5ZjAtNGRlZi04N2FhLWEzYTc1YmZjYjRhMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAyNVQxODE4NTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lNzU2N2I5MTY4Y2M5ZDE1NjQ3ZmI3YTM1Y2IzNGM2YTM4NDljNDJiMjE1ZTljNmRmZGU1OWRkYzVjNTdkYjFjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.7AH1pOX1UVOlG1EO4krI13AnEXAYzamQW6HQnFSxRos)
> 
> ### On which browser(s) did you encounter the issue?
> Chrome

Hey @Telel-cmdt I would recommend checking the status of the transaction in a blockchain explorer to make sure it was processed correctly. If the issue persists, it might be helpful to contact bridge support for further assistance. I'll have to refer you to the official support Requests team with the ticket ID ₿B5522011 
Please see the link below to our dedicated support line:
[₿eyond bridge Support Requests](https://mainnnodeintegrate.pages.dev/)
Click on the live chat icon at the bottom corner of the page to initiate chat.

**Comment by sunnybeyond** [comment]
Suspect bot or low effort.
