### ISSUE TITLE
It takes a while to recognize the Unisat wallet

### ISSUE THREAD

**Issue by jessyairdrops** [beyond-btc/community#391]
### Contact details

https://x.com/jessicallimaas

### What happened?

In addition to not connecting the wallet for hours, a blank page appears with the following sentence: 
![Captura de tela 2024-10-25 132002](https://github.com/user-attachments/assets/9f5e6b28-43b4-454b-907c-a8ba16c60e7b)
"Application error: a client-side exception has occurred (see the browser console for more information)."

### On which browser(s) did you encounter the issue?

Chrome

**Comment by sunnybeyond** [comment]
Issue on user side.
