### ISSUE TITLE
When I interact with the ₿eyond bridge..:  in addition to it disconnecting from the metamask, it is taking a long time to complete a transfer, taking 6 to 7 hours, more to complete. the browser I'm using is Opera.

### ISSUE THREAD

**Issue by edsonkenzie** [beyond-btc/community#392]
### Contact details

edsonrelb@gmail.com, https://x.com/beyond__tech, @EdsonBotelho20

### What happened?

What happened?
A: Well, I connect to metamask and the connection keeps dropping, so every time I do the bridge I have to connect again, besides it taking a long time to complete the bridge, another thing is that I linked to metamask, UniSat and Phantom Solana wallets but I can't bridge it with Solana.
Follow the image below of the operations:
![Demorando pra concluir Beyond](https://github.com/user-attachments/assets/b6fd570c-367f-4185-8b3b-a54e2d49e4da)
![Solana não acessiva](https://github.com/user-attachments/assets/47470b49-1864-44ab-ba95-da258aa8f839)
![Beyond sem solana](https://github.com/user-attachments/assets/a181d304-c331-47b0-b282-9f4ff142cda2)
![Desconectou Beyond](https://github.com/user-attachments/assets/3fcfc5f1-aabc-4ba1-b425-8238f0f42148)

### On which browser(s) did you encounter the issue?

Chrome, Metamask, Other (please specify)

**Comment by sunnybeyond** [comment]
Well, Solana is not available yet. Eitherway, not enough info to work with.
