### ISSUE TITLE
the EVM wallet does not connect - BUG

### ISSUE THREAD

**Issue by LeocryptoGIT** [beyond-btc/community#394]
### Contact details

@Leocryptotwitte

### What happened?

I was expecting Bug, but instead wallet not conected

1. Navigate to 'Bridge'
2. Click on 'connect you wallet ETH'
  * BUT not connect.
![Captura de tela 2024-10-25 144144](https://github.com/user-attachments/assets/1ac14d57-db1c-44f9-b59e-d8519c6f1511)

I have attached a screenshot to illustrate the issue.

### On which browser(s) did you encounter the issue?

Chrome, Metamask

**Comment by sunnybeyond** [comment]
Suspect bot or low effort.
