### ISSUE TITLE
Transactions between bridges are very slow.

### ISSUE THREAD

**Issue by edsonkenzie** [beyond-btc/community#395]
### Contact details

edsonrelb@gmail.com, https://x.com/beyond__tech, @EdsonBotelho20

### What happened?

The bridge between Eth sepolia and
BNB Chain Testnet, it is very slow as shown in the attached image:
![Trazações Lenta Beyond](https://github.com/user-attachments/assets/bdfbcd4c-5862-476e-9b13-e9f1fe0f87a7)

### On which browser(s) did you encounter the issue?

Metamask, Other (please specify)

**Comment by sunnybeyond** [comment]
Suspect bot or low effort.
