### ISSUE TITLE
Problem with the bridge

### ISSUE THREAD

**Issue by tonyfeno** [beyond-btc/community#396]
### Contact details

https://x.com/SuasaTony97458

### What happened?

Hello my friends, I'm having trouble connecting the wallet, but it worked. Many times the process stops out of nowhere. The big problem is the delay of the bridge. Thanks.

![g12](https://github.com/user-attachments/assets/1c89e2e4-b39a-4377-a80c-54bde2e67366)

### On which browser(s) did you encounter the issue?

Chrome, Metamask, Brave

**Comment by sunnybeyond** [comment]
Suspect bot or low effort.
