### ISSUE TITLE
when I interact with the bridge, the network becomes very slow to complete

### ISSUE THREAD

**Issue by Renato10melo** [beyond-btc/community#398]
### Contact details

when I interact with the bridge, the network becomes very slow to complete, taking a long time to complete.

### What happened?

I was expecting X, but instead Y happened!

1. Navigate to '...'
2. Click on '...'
3. Scroll down to '...'
4. Observe the error / unexpected behavior

I have attached a screenshot to illustrate the issue.

### On which browser(s) did you encounter the issue?

Chrome, Metamask

**Comment by sunnybeyond** [comment]
Suspect bot or low effort.
