### ISSUE TITLE
[When I interact with the ₿eyond bridge...]: it gave error 404 response 

### ISSUE THREAD

**Issue by SamRhex** [beyond-btc/community#399]
### Contact details

samsononu07@gmail.com, samrex0895 on discord

### What happened?

I clicked on the “bridge” icon (under Protocol) and it gave “error 404” response 
![IMG_9692](https://github.com/user-attachments/assets/85b1b79b-b0ee-4d12-ae0b-e8c09795afc1)
![Uploading IMG_9683.jpeg…]()

### On which browser(s) did you encounter the issue?

Safari, Edge

**Comment by SamRhex** [comment]
Sincerely happy to be part of this amazing community and innovative project.
I'm really intrigued by how it could simplify transactions and make it easier for users to move assets between different blockchains. Plus, the potential for new applications and innovations in the crypto space is super exciting!
I hope for the best

**Comment by sunnybeyond** [comment]
Suspect bot or low effort.
