### ISSUE TITLE
Transaction Slow Bridge

### ISSUE THREAD

**Issue by EvandroBarbosa** [beyond-btc/community#400]
### Contact details

@EmbCryptoDev

### What happened?

When making the bridges, there has been a very long delay, leaving the user discouraged with the delay.
![testnet](https://github.com/user-attachments/assets/57ee1142-5946-4f28-a917-6da789c468e8)

I can't bridge Bitcoin Testnet to another network is not recognizing that it has a balance in my Unisat wallet

### On which browser(s) did you encounter the issue?

Metamask, Edge

**Comment by sunnybeyond** [comment]
Can't change how fast the network is.
