### ISSUE TITLE
[When I interact with the ₿eyond bridge...]: I am experiencing slowness in some transactions

### ISSUE THREAD

**Issue by FNK2802** [beyond-btc/community#401]
### Contact details

https://x.com/fagneramostenes

### What happened?

I am experiencing slowness in some transactions, and difficulty connecting the metamask to a specific browser, my BTC balance does not appear when bridging the BTC ETH Sepolia network
![bo beyond](https://github.com/user-attachments/assets/9d995f5c-6fcd-48a8-a0e8-943a4f5fb2e1)
![bo 02](https://github.com/user-attachments/assets/209aae95-a20b-4e7d-aabf-54acb669da0f)

### On which browser(s) did you encounter the issue?

Chrome, Metamask, Brave

**Comment by Orso218GT** [comment]
you have to set your unisat wallet and go over
![unisat advance set](https://github.com/user-attachments/assets/8da930e4-bd2f-4918-bd31-ba8bbfd5d402)

**Comment by sunnybeyond** [comment]
Suspect bot or low effort.
