### ISSUE TITLE
₿eyond bridge. can't connect my metamask automaticaly

### ISSUE THREAD

**Issue by Vagabondo19** [beyond-btc/community#402]
### Contact details

roru2352@gmail.com

### What happened?

Hi developers, I want to contribute with my feedback, every time I try to connect my metamsk wallet, this is not recognized by the bridge and I have to connect via extension as you can see in the image, even if otherwise it works quite well, thanks for this opportunity. 
![Schermata 2024-10-26 alle 00 19 13](https://github.com/user-attachments/assets/8823b822-f8a5-4f7d-9b8b-979a1d7cc9e7)

### On which browser(s) did you encounter the issue?

Chrome

**Comment by Vagabondo19** [comment]
Another thing is that my balance is not updated, it still remains $123.78
![Mah2544](https://github.com/user-attachments/assets/b4fddc2d-5b4c-428b-b5f7-ea013f8bc194)

**Comment by sunnybeyond** [comment]
Suspect bot or low effort.
