### ISSUE TITLE
MY FEEDBACK ABOUT TESTNET

### ISSUE THREAD

**Issue by Orso218GT** [beyond-btc/community#403]
### Contact details

f.dsspower@gmail.com

### What happened?

Hi guys, as a tester, I like to try new projects, yours has some problems with the speed of the transactions, another thing, I don't understand why I can't bridge back even if I have a little of tBTC? I understand that you are still at the beginning and I am sure that you are working hard to offer the best experience to the user, and I can't see the balance of the BTC tokens in the token selection phase? anyway well done guys, keep developing.
![balance](https://github.com/user-attachments/assets/c0fa5c30-0f0b-4ede-98a1-5c7402ffce70)

### On which browser(s) did you encounter the issue?

Chrome, Metamask

**Comment by sunnybeyond** [comment]
Suspect bot or low effort.
