### ISSUE TITLE
I CAN NOT BRIDGE BACK FROM BTC TO SEPOLIA

### ISSUE THREAD

**Issue by Orso218GT** [beyond-btc/community#404]
### Contact details

f.dsspower@gmail.com

### What happened?

Hello guys, thanks for this interesting project, I wanted to ask you if it is possible to bridge my funds back? a big hug and I wish you a beautiful ![bridge beyond](https://github.com/user-attachments/assets/be6a6bf8-3dd0-402c-8d3b-d08643d483ba)

### On which browser(s) did you encounter the issue?

Chrome, Metamask

**Comment by Dappsnode** [comment]
@Orso218GT it's usually possible to bridge your funds back, but it depends on the specific platforms and networks you're using. Make sure to check the bridging process and any fees involved.

**Comment by Orso218GT** [comment]
Thank you so much for the quick response, this shows that you are focused
on the community to improve the project.
right now I will try your bridge again, and remember,
 if you want to include me in the white list for the mint of your
desirableNFT, feel free to include me.😊
 Have a Good day

My wallets:
*EVM: **0x48056e2D99CD5b1dAe0492704a0c4482D00eC43C*
*BTC: **bc1p2ha03aqn096uz0wcwl2v0jtr9erne8e8pwzqfm49smuedscrezas0tnx2f*

**Comment by sunnybeyond** [comment]
Suspect bot or low effort.
