### ISSUE TITLE
[When I interact with the ₿eyond bridge Bitcoin Testnet to Sepolia Testnet]: 

### ISSUE THREAD

**Issue by Casthely** [beyond-btc/community#405]
### Contact details

https://x.com/Helder_Casthely

### What happened?

All cryptocurrency options from Bitcoin Testnet to Sepolia or BNB have zero balance.

Due to the lack of balance, it is impossible to test this option.

![Beyond](https://github.com/user-attachments/assets/183e6907-9a3e-4cd9-a50b-b7bc421e85c5)

### On which browser(s) did you encounter the issue?

Chrome, Metamask, Brave, Edge

**Comment by sunnybeyond** [comment]
Suspect bot or low effort.
