### ISSUE TITLE
[When I interact with the ₿eyond bridge Sepolia to Bitcoin]: 

### ISSUE THREAD

**Issue by Casthely** [beyond-btc/community#406]
### Contact details

https://x.com/Helder_Casthely

### What happened?

For both BRC-20 and Runes, on this day 10/25 at 10:32 pm the bridge button does not enable clicking.
![Captura de tela 2024-10-25 222656](https://github.com/user-attachments/assets/90422903-d0f1-4da3-993a-908ee1f9e079)
![Captura de tela 2024-10-25 222937](https://github.com/user-attachments/assets/8aadbd6b-c3dd-41b6-b71a-23245446d8cb)

### On which browser(s) did you encounter the issue?

Chrome, Metamask, Brave, Edge

**Comment by sunnybeyond** [comment]
Because you didn't select BTC testnet
