### ISSUE TITLE
transactions do not appear after confirmation

### ISSUE THREAD

**Issue by cajapera** [beyond-btc/community#408]
### Contact details

rapp.cesar@gmail.com

### What happened?

I was expecting X, but instead Y happened!

1. Navigate to 'chome'
2. Click on '...'
3. Scroll down to '...'
4. Observe the error / unexpected behavior

I have attached a screenshot to illustrate the issue.
Hello core team beyond yesterday I was doing some bridges and it stopped after the transaction was approved but the transactions do not show that they are completed only after refreshing the page

### On which browser(s) did you encounter the issue?

Chrome

**Comment by sunnybeyond** [comment]
Suspect bot or low effort.
