### ISSUE TITLE
[When I interact with the ₿eyond bridge it doesn't connect the wallets and it's slow

### ISSUE THREAD

**Issue by julianobrasil2024** [beyond-btc/community#410]
### Contact details

https://x.com/Juliano25815455

### What happened?

Using the unisat and metamask wallet I can't connect both at the same time in the same browser. I had to connect one in each browser and copy the transfer wallet, making it difficult to use the bridge, increasing the slowness of the bridge.
![Capturar](https://github.com/user-attachments/assets/d56781e0-7579-4ba6-989c-2710e408a31f)

### On which browser(s) did you encounter the issue?

Chrome, Metamask

**Comment by sunnybeyond** [comment]
Suspect bot or low effort.
