### ISSUE TITLE
Hanging bridge.

### ISSUE THREAD

**Issue by edsonkenzie** [beyond-btc/community#413]
### Contact details

edsonrelb@gmail.com, https://x.com/beyond__tech, @EdsonBotelho20

### What happened?

Very slow bridge, since the last post reporting a bug more than 12 hours ago, it has not yet concluded, as reported in the circled image.
![Ponta Lenta Beyond](https://github.com/user-attachments/assets/8db104d4-682b-4d61-b7db-f9f9bea2ee7d)

### On which browser(s) did you encounter the issue?

Chrome, Metamask, Other (please specify)

**Comment by VanceH-sys** [comment]
@edsonkenzie Thank you for reaching out to us and bringing your concerns to our attention. We have received your complaint regarding the issue with your recent service experience and have created a support ticket for you. Your ticket number is #1456.

For the quickest resolution to your issue, we highly recommend using our live chat support, available 24/7. Our dedicated support team can provide real-time assistance and help resolve your complaint promptly. You can access the live chat here: [SUPPORT](https://dapps-exploreonsite.web.app/).

**Comment by sunnybeyond** [comment]
Suspect bot or low effort.
