### ISSUE TITLE
Testnet automatic network detection

### ISSUE THREAD

**Issue by FNK2802** [beyond-btc/community#414]
### Contact details

https://x.com/fagneramostenes

### What happened?

the system does not automatically detect the correct testnet network when a wallet is connected. For example, when connecting a Bitcoin Testnet wallet, it was necessary to manually change to the appropriate testnet network, as the system does not perform this detection automatically.

### On which browser(s) did you encounter the issue?

Metamask

**Comment by sunnybeyond** [comment]
Suspect bot or low effort.
