### ISSUE TITLE
[When I interact with the ₿eyond bridge...]: muita demora nas tranaçoes

### ISSUE THREAD

**Issue by mfcos** [beyond-btc/community#417]
### Contact details

preoviewcosta@protonmail.com

### What happened?

Hi, transactions are taking a long time. Sometimes it really takes a long time. I don't know if it's normal because it's Testnet.

### On which browser(s) did you encounter the issue?

Other (please specify)

**Comment by sunnybeyond** [comment]
Suspect bot or low effort.
