### ISSUE TITLE
slowness on the bridge

### ISSUE THREAD

**Issue by tonyfeno** [beyond-btc/community#418]
### Contact details

https://x.com/SuasaTony97458

### What happened?

Hello friends, I'm having a lot of trouble making the bridge between the Sepolia testnet and the BTC testnet. It's taking a long time. I wonder if changing the wallet could solve it. Thanks.
![b1](https://github.com/user-attachments/assets/ea568a20-0764-447c-9c8c-65789fbf6974)

### On which browser(s) did you encounter the issue?

Chrome, Metamask, Brave

**Comment by sunnybeyond** [comment]
Suspect bot or low effort.
