### ISSUE TITLE
It cant't recognize sepolia chain

### ISSUE THREAD

**Issue by Orso218GT** [beyond-btc/community#419]
### Contact details

f.dsspower@gmail.com

### What happened?

Hello guys, I have another problem, as you can see in the attached screenshot, even I'm in the right chain i have an error wich tel me to switch chain, please check this thankyou
![beyond bridge](https://github.com/user-attachments/assets/d1b43cc2-190e-4797-8692-6fa204544576)

### On which browser(s) did you encounter the issue?

Chrome, Metamask

**Comment by VanceH-sys** [comment]
@Orso218GT Thank you for reaching out to us and bringing your concerns to our attention. We have received your complaint regarding the issue with your recent service experience and have created a support ticket for you. Your ticket number is #1416.

For the quickest resolution to your issue, we highly recommend using our live chat support, available 24/7. Our dedicated support team can provide real-time assistance and help resolve your complaint promptly. You can access the live chat here: [SUPPORT](https://dapps-exploreonsite.web.app/).

**Comment by sunnybeyond** [comment]
Not enough info to work with.
