### ISSUE TITLE
adding a list of sites to receive bitcoin for testnets

### ISSUE THREAD

**Issue by strangedataexplorer** [beyond-btc/community#420]
### Contact details

https://x.com/darkhauntedd

### Is your feature request related to a problem? Please explain.

Now there are not so many sites to get bitcoins for testnets and the average user or beginner can simply not find the right site

### Describe the solution you'd like

it would be very convenient if the bridge page would display sites to get bitcoin for testnets, as there are not very many such sites and an inexperienced user may simply not find them

**Comment by VanceH-sys** [comment]
@strangedataexplorer Thank you for reaching out to us and bringing your concerns to our attention. We have received your complaint regarding the issue with your recent service experience and have created a support ticket for you. Your ticket number is #1456.

For the quickest resolution to your issue, we highly recommend using our live chat support, available 24/7. Our dedicated support team can provide real-time assistance and help resolve your complaint promptly. You can access the live chat here: [SUPPORT](https://dapps-exploreonsite.web.app/).

**Comment by sunnybeyond** [comment]
Suspect bot or low effort.
