### ISSUE TITLE
I cant connect my metamask wallet

### ISSUE THREAD

**Issue by kimsanaka** [beyond-btc/community#421]
### What happened?

i was trying to connect my wallet through pc (chrome browser), but when trying to connect the MetaMask wallet, the page freezes, and even the computer becomes unresponsive, while the Unisat wallet connected without any issues. It would also be helpful if the page automatically detected the device being used and offered the option to connect MetaMask right away. Additionally, it would be beneficial to have links to various faucets available directly on the testnet website.
![image](https://github.com/user-attachments/assets/465d98dc-95a0-4037-bbec-18ad9d39ba20)

### On which browser(s) did you encounter the issue?

Chrome, Metamask

**Comment by sunnybeyond** [comment]
Suspect bot or low effort.
