### ISSUE TITLE
Suggestions from me

### ISSUE THREAD

**Issue by beyondmes** [beyond-btc/community#422]
### Is your feature request related to a problem? Please explain.

first of all it was interesting experience, now to features, that i can suggest to implement:

### Describe the solution you'd like

Enable automatic detection of installed wallets (e.g., MetaMask) and prompt users to connect upon loading the page, reducing unnecessary steps.
Add a visible connection indicator, such as a green "Connected" icon, along with clear error messages if connection issues arise, making navigation easier
Provide direct links to testnet faucets for networks like Sepolia and Bitcoin on the page, so users can easily acquire test tokens. 

Add tooltips or brief explanations next to fields and options (like "Runes" or "Sepolia Testnet") to make the interface more intuitive.
Implement a transaction log showing recent transactions and their statuses, allowing users to track completed and pending transactions.

These improvements would make the interface more user-friendly, intuitive, and efficient. Thankds for reading

**Comment by sunnybeyond** [comment]
We already have most of these features...
