### ISSUE TITLE
metamask issue

### ISSUE THREAD

**Issue by riponsad** [beyond-btc/community#423]
### Contact details

Discord Id -  ripon266

### What happened?

I am trying to use testnet then open site their have 3 wallet metamask/ magic edn & okx only metamask available then i am try to connect my wallet but didn’t received popup on my wallet after 5/6 times refresh site then connect wallet. Hopefully team will look it & bridge time i see 15 minutes it’s too much fix & decrees time like 5/10. Also should add faucet options on site. Thanks in advance🙏

### On which browser(s) did you encounter the issue?

Metamask

**Comment by sunnybeyond** [comment]
Suspect bot or low effort.
