### ISSUE TITLE
[Enhance the ₿eyond UI with...]: Verification code

### ISSUE THREAD

**Issue by Adufeteminikan** [beyond-btc/community#425]
### Contact details

adekunlesundayadufe@gmail.com or X @_AdFT_

### Is your feature request related to a problem? Please explain.

It's stressful typing the verification code one after the other, instead of copying and pasting it

### Describe the solution you'd like

The user interface is a very key part of the excellence of the project l, and as important as verification is it should not be made stressful, due to the single imputation of the codes, the codes should be easily copied from the mail and pasted on the site.

**Comment by sunnybeyond** [comment]
Suspect bot or low effort.
