### ISSUE TITLE
Feedback about Beyond Bridge

### ISSUE THREAD

**Issue by Latinos12** [beyond-btc/community#428]
### Contact details

jumper20104@gmail.com

### What happened?

Browser: Chrome 130.0.6723.92 64 bit. 
Wallet: Metamask, Unisat
Bridging from EVM networks to the Bitcoin Testnet worked relatively well overall, but I did face some challenges. There were moments when the bridge button was inactive, and I found that the balances of test tokens were not visible, making it difficult to initiate transfers. In contrast, transfers between EVM networks were smooth and encountered no significant issues after multiple attempts.

Nonetheless, there are several areas that need enhancement. The bridge currently does not allow for the transfer of BRC-20 or Runes tokens, which was a letdown. Additionally, while the expected commission is eventually shown in the wallet during the signing of transactions, it would greatly improve the user experience if this information were readily available in the interface from the start. I hope these concerns, particularly regarding the Bitcoin Testnet, will be resolved in upcoming updates.
![image](https://github.com/user-attachments/assets/118acd54-28c0-4838-8596-a846e9c4187e)

### On which browser(s) did you encounter the issue?

Chrome, Metamask

**Comment by sunnybeyond** [comment]
Feedback will not count. Event is over.
