### ISSUE TITLE
Network display

### ISSUE THREAD

**Issue by c1acege** [beyond-btc/community#429]
### What happened?

I wanted to try to interact with the beyond bridge and ran into a situation that confused me. The screenshot I attached shows that I wanted to transfer my tokens from SepoliaETH to Runes Bitcoin Testnet. After connecting Metamask to the site I saw a message that I had to change the network in my wallet to Sepolia Testnet, and I thought that was it, but as it turns out I didn't change the network in my Bitcoin wallet. Because of this I sat for a few minutes wondering what the problem was and only found out the solution by contacting the project's Discord server (thank you). The purpose of my issue is to suggest adding a hint for the user to change the network in the Unisat wallet as well. I think I'm not the first and not the last to encounter such a simple but ambiguous error. Thanks.
![image](https://github.com/user-attachments/assets/9e5ea255-87cd-4bc7-926d-9cd63287522f)

**Comment by sunnybeyond** [comment]
Feedback will not count. Event is over.
