### ISSUE TITLE
When I interact with the ₿eyond bridge I can't connect the wallet

### ISSUE THREAD

**Issue by rogeriowok** [beyond-btc/community#431]
### Contact details

https://x.com/WojcikRogerio

### What happened?

I try to connect the unisat wallet, the balance is zero, but I have tbtc in the wallet. The metamask does not connect at all. And the bridge page is crashing a lot. I use chrome browser
![Beyond](https://github.com/user-attachments/assets/1f886097-d47b-40b1-a5cb-c7b18f2574b4)

### On which browser(s) did you encounter the issue?

Metamask, Other (please specify)

**Comment by Elsiehwoods** [comment]
@rogeriowok You're experiencing transcript error. It sounds like your query would be best dealt with by the support team.
I'll have to refer you to the official support live chat with the ticket ID UNI07638
Please see the link below to our dedicated support line:
[Unisat Network DApps Support Ticket Requests.](https://thedappsupport.live/

)
 Click on the live chat icon at the bottom corner of the page to initiate chat with a live support agent.

**Comment by sunnybeyond** [comment]
EVENT IS CLOSED - PLEASE ADD NO MORE BUGS OR FEEDBACK - THEY WILL NOT COUNT FOR REWARDS
