### ISSUE TITLE
Feedback about Bridge

### ISSUE THREAD

**Issue by tluulw** [beyond-btc/community#432]
The bridge is very good and handy to use.
I'd add a guide to using the bridge for better interaction)
![image](https://github.com/user-attachments/assets/771c25d4-e73c-4831-8a43-ceca8a8eb75c)

**Comment by sunnybeyond** [comment]
EVENT IS CLOSED - PLEASE ADD NO MORE BUGS OR FEEDBACK - THEY WILL NOT COUNT FOR REWARDS
