### ISSUE TITLE
Feedback on beyond

### ISSUE THREAD

**Issue by Kodark220** [beyond-btc/community#50]
### Contact details

x.com/vintage8080

### What happened?

I was unable to connect my metamask wallet to Beyond from the homepage, I later had a breakthrough but after brideging from sepolia to btc(runes) it disconnected . tried connectiong after but was unable. 
my bnb faucet is not  also showing from beyond Homepage when i checked through my faucet from the Homepage. 
i also cant bridge from bitcoin to other chains and i got tbtc in the wallet.

All in all the bridge is fair  but I feel you guys can do better by adding the percent of amount one wishes to bridge on the UI/UX

The Team should also make the page to be more responsive so as to be able to connect to wallets with ease!

Also the UI/UX should also have more feastures where one can adjust gas and also slippage   
![tbtc2](https://github.com/user-attachments/assets/7fb28b58-4879-47cc-a40f-c2aca11f0ce4)

![tbtc1](https://github.com/user-attachments/assets/1c047498-e1d2-42d0-8c01-e26fb46c3d49)

### On which browser(s) did you encounter the issue?
CHROME
_No response_

**Comment by sunnybeyond** [comment]
No information we can create a case with.

**Comment by Kodark220** [comment]
What I am trying to say is  I'm experiencing issues connecting my MetaMask wallet to the Beyond platform. Initially, I succeeded, but the connection dropped after bridging from Sepolia to BTC (RUNES). Reconnection attempts failed.

other Issues faced 

1. BNB faucet balance doesn't display on the Beyond homepage.
2. Unable to bridge Bitcoin to other chains; even after having TBTC  in wallet.




To elevate the experience:

1. Streamline wallet connection and bridging processes.
2. Enhance user experience with Percentage-based bridging amount selection, adjustable gas fees, slippage control and enhanced responsiveness for seamless wallet connections
