### ISSUE TITLE
Add Max button

### ISSUE THREAD

**Issue by dashok222** [beyond-btc/community#52]
### Contact details

https://x.com/Sasquat97266489

### Is your feature request related to a problem? Please explain.

Thank you for the smooth expierence bridging funds from ETH Sepolia to BTC testnet3. I have faced only one issue, which displays incorrect ETH value (Check solution screenshot). 
BTC testnet bridge wasn't working for me. I basically can't send the transaction from Unisat. I think there is problem with generating such transaction in Unisat wallet.

### Describe the solution you'd like

I think you should add max button to this "amount" field 
![add max button](https://github.com/user-attachments/assets/89d614e9-b8d8-46e6-ae59-7311ec26c21f)

**Comment by sunnybeyond** [comment]
Even though the suggestions are good, this is just too hurriedly written for me to accept.
