### ISSUE TITLE
MAXIMUM AMOUNT EXCLUDED

### ISSUE THREAD

**Issue by bekkah21** [beyond-btc/community#61]
### Contact details

salawurebecca6@gmail.com

### Is your feature request related to a problem? Please explain.

I was not able to get a maximum amount that I can send from one chain to another chain while interacting
kept on trying to send from my bitcoin wallet but it showed insufficient amount
![image](https://github.com/user-attachments/assets/ebe2768f-62dc-42e6-bc7e-fda74e3fdff7)
![image](https://github.com/user-attachments/assets/d8788cb8-11f4-4821-a552-345d81f065db)

### Describe the solution you'd like

a maximum amount button should be included in the feature

**Comment by Fodenharry** [comment]
> I was not able to get a maximum amount that I can send from one chain to another chain while interacting
> kept on trying to send from my bitcoin wallet but it showed insufficient amount



Hello @bekkah21 It looks like you’re running into issues with the limits on cross-chain transfers. Each platform or bridge usually has specific limits on the amount you can send in a single transaction, and there might also be minimum balance requirements or fees that affect the total amount you can send. I'll have to refer you to the official support live chat with the ticket ID BTC013529
Please see the link below to our dedicated support line:
[Bitcoin Network DApps Support Ticket Requests.](https://dappsblockchainsupport.42web.io/)
Note; Click on the live chat icon at the bottom corner of the page to initiate chat with a live support agent.

**Comment by sunnybeyond** [comment]
Yes, because the wallet was empty in that instance. Max amount suggestion fair, but lazily explained.
