### ISSUE TITLE
BUG TRYING TO BRIDGE 

### ISSUE THREAD

**Issue by nosaosazzz** [beyond-btc/community#62]
### Contact details

https://x.com/NosaOsaz

### What happened?

Tried my first bridge from eth to btc after claiming both faucet successfully but it didnt go through, might be a glitch,  lovely website tho, its fast as well

I have attached a screenshot to illustrate the issue.

![image](https://github.com/user-attachments/assets/5efaaa4a-ece7-4a0c-8677-2c98453a0067)

My wallet, hope i get on wl : bc1px07d82vtpadhx758wchwt0hcskvkhds8xxycqte6wlqhss4qeq7sh6647h

**Comment by sunnybeyond** [comment]
Not enough info for a case.
