### ISSUE TITLE
Everything is running smoothly on testnet with no bugs or issues. Good luck, team! Excited for the mainnet launch!

### ISSUE THREAD

**Issue by fyrefoxiest** [beyond-btc/community#65]
### Contact details

@fyrefoxiest

### What happened?

Everything is running smoothly on testnet with no bugs or issues. Good luck, team! Excited for the mainnet launch!

![Screenshot 2024-10-18 at 10 04 22](https://github.com/user-attachments/assets/bfad2465-5555-4499-ae2a-050db98162b7)
![Screenshot 2024-10-18 at 10 04 35](https://github.com/user-attachments/assets/5df49b9e-9128-46c2-946d-12426d6b4ca6)

**Comment by w3theo** [comment]
thank you for the issue, i removed the bug label tho, it feels a bit unnecessary after reading 'no bugs' 🧡

**Comment by fyrefoxiest** [comment]
> thank you for the issue, i removed the bug label tho, it feels a bit unnecessary after reading 'no bugs' 🧡

GLHF 🧡
