### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by daisydee1504** [beyond-btc/community#68]
I had issues connecting to the website on my PC but when I used my phone, it opened quite immediately 
After several attempts, was able to open it on pc 
I was able to claim all my faucets successfully 
Approving beyond btc on Sepolia ethereum took less than a minute
I couldn’t bridge from Bitcoin testnet to sepolia testnet though. I claimed my Bitcoin testnet and it’s showing in my wallet but it’s not showing when I want to use. 
Bridging from Sepolia Testnet to Bitcoin Testnet was super fast with no issues. 
Bridging from bnb to eth went fast too
 Really nice website, smooth and fast but more work should be done on bridging btc testnet to sepolia👍

bc1pq0llqg3qrepc29q5xvhvuqrd70gglaqjs6hkrnu3neqfmxgltg8sq7sgvn

**Comment by sunnybeyond** [comment]
Not enough info for a case.

**Comment by mubrickjr** [comment]
Bridging from Eth to BNB to BTC was smooth and fast, I had no issue with that.
Also the UI/UX is easy, good looking, I had a great and satisfied experience.

had quite bad experience when trying to use my PC
I personally believe y'all can give slight improvement and it's good to go
