### ISSUE TITLE
General overview 

### ISSUE THREAD

**Issue by Henry5778** [beyond-btc/community#71]
The UI interface is pretty clean and straightforward and user friendly I love it! 
It also works well on the mobile mode which is something most testnet bridges lack

I really wished there's was an easier way to get testnet token...getting sepolia eth wasn't so difficult as it is a very common testnet token, but getting the bnb testnet was different I had a deposit little money on mainnet before the token was sent over 
Btc testnet token was the worst. I suggest maybe a discord section in beyond where people can discuss more about the bridge & likely issues faced /improvement.
A discord bot that sends testnet token will be fantastic 

The single chain bridge works good for me  very fast and seamless
![Screenshot_20241018-061953_MetaMask](https://github.com/user-attachments/assets/6c36a85d-59e3-4855-a226-fac438e92d9c)

But the crosschain Bridging isnt yet seamless and still needs improvement 
Bridging takes too long to confirm and wallet balances doesn't come up till after sometime when Bridging cross-chain 
![Screenshot_20241018-070335_Gallery](https://github.com/user-attachments/assets/b2f5e30a-69cf-4b16-b2ae-53bf71d358c3)
From evm to btc doesn't let me bridge
I'd still try out on a pc for better experience 
Thanks beyond 👋🏼

**Comment by sunnybeyond** [comment]
You are using a real BTC address, not testnet. Can't do much about testnet faucets outside our control.
