### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by hyperlimit427** [beyond-btc/community#72]
### Contact details

https://x.com/Richard76966104

### What happened?

When sending any amount, the interface constantly displays the same value regardless of the actual size of the transaction, which can be misleading. In addition, the estimated bridge fee is not displayed in the interface and is only visible in the wallet, which reduces transparency for users. While transactions between the Bitcoin Testnet and EVM networks work well, there is a problem when trying to send funds from the Bitcoin network: the necessary confirmation to proceed with the transaction is missing, making it impossible to complete the transfer. These problems interfere with the overall usability and understandability of the bridge.
![Без имени1](https://github.com/user-attachments/assets/b00a3018-45bc-4477-b102-8991549b2ef6)
![Без имени2](https://github.com/user-attachments/assets/0e3ddb33-f98b-40be-8d89-37bb39f61446)
![image](https://github.com/user-attachments/assets/e64c2ed7-b282-468b-bb84-304a8707e787)

### On which browser(s) did you encounter the issue?

Chrome

**Comment by sunnybeyond** [comment]
You didn't have enough funds in the BTC wallet to do the transfer. You tried to send the full amount you had.
