### ISSUE TITLE
Paste Destination Wallet

### ISSUE THREAD

**Issue by KingGOE9** [beyond-btc/community#74]
### Contact details

banireadeyemi9@gmail.com

### Is your feature request related to a problem? Please explain.

Lack of paste destination wallet option as alternative to connecting destination wallet

### Describe the solution you'd like

Starting the testnet, I had issues with connecting my EVM wallet as a destination wallet then I wondered why it did not have the "paste destination wallet" option as an alternative to connecting destination wallet. I feel the option would be really helpful as most of the bridges that I know that require you to connect destination wallet only do it because they need you to pay a form of fee on the destination chain too. This will also encourage mobile wallet support, as you can't connect both EVM and BTC wallets in most mobile wallets.
Also, Gas cost/estimates would be nice. I spent way too much time looking for enough tBTC for the BTC transactions.

**Comment by sunnybeyond** [comment]
You can just paste wallet addresses? This is already possible...
