### ISSUE TITLE
wrong ETH Value when bridge sepolia to bitcoin Bridge | Beyond

### ISSUE THREAD

**Issue by Meshineshi** [beyond-btc/community#77]
### Contact details

x.com/sentrakaspila

### What happened?

Gm! here's my feedback about bridge Beyond

I have attached a screenshot to illustrate the issue.
[
![22](https://github.com/user-attachments/assets/664a9c95-4c42-4b01-8165-abf59cf7e4c2)
](url)

![33](https://github.com/user-attachments/assets/115914d6-71d3-499c-9e73-e04d2dafa12a)

![44](https://github.com/user-attachments/assets/d1d0e34c-04ba-4f70-bb91-9c267e647c73)

### On which browser(s) did you encounter the issue?

Brave

**Comment by sunnybeyond** [comment]
So... what is the issue?
