### ISSUE TITLE
Appreciation and need for improvement on the website design 

### ISSUE THREAD

**Issue by Immortal423** [beyond-btc/community#78]
### Contact details

https://x.com/D_wiz423?s=09

### What happened?

Gm Gm
I already spoke about this issue on the Discord support.
So I hope its the same person that views this. 
Different issues encountered on the site while bridging often show the same error  message, not allow users to know the specific issue that caused this. It would be nice if this could be changed. 
You could reach out to me for improvements.
I'd be happy to help. 
Your Ui/UX looks nice tho.
Very simple and creative.
![Screenshot_20241018-081128_Mises](https://github.com/user-attachments/assets/fd641792-af2e-4f88-9d18-6b37e5386d12)

My wallet 0x5Caa058F3919Cf0b3446030def8dbe45102E6095

**Comment by Immortal423** [comment]
Was encountered on mises browser

**Comment by Immortal423** [comment]
tb1pehafdg8rclvtjx4mynry62v6kmrvev3f3rsyalmaekk22hzng4uqt2sl5s

Testnet wallet. Disregard the Taproot wallet, in the initial post

**Comment by w3theo** [comment]
this has been solved (#191)

**Comment by sunnybeyond** [comment]
The gas fee required was manually set too high by user.

**Comment by Immortal423** [comment]
bc1pdkgkfreju65pfmxrhsm2kjhf8dtlfezjsmxmysakru40vdcrtyzsjfv9qs

Taproot wallet
