### ISSUE TITLE
feedback

### ISSUE THREAD

**Issue by stagaplaetsu0a** [beyond-btc/community#81]
The Beyond platform impressed me with its simple and intuitive interface. I made several transactions between networks, and they were completed almost instantly. I especially liked that the network balance is displayed immediately—this saves time and simplifies the swap process.

I would only like to add a feature for estimating the transaction completion time, so it would be clear how long the transfer will take depending on the network load. Otherwise, my experience with the platform was very positive.

**Comment by sunnybeyond** [comment]
There already is an estimation time implemented...
