### ISSUE TITLE
feedback bug

### ISSUE THREAD

**Issue by Owgwen** [beyond-btc/community#85]
The web can't connect the EVM extension in the Chrome browser, so I use the Edge browser for ETH-BTC transactions, then I return the BTC-ETH in Chrome
<img width="960" alt="Screenshot 2024-10-18 181436" src="https://github.com/user-attachments/assets/bb6ff8b4-dea1-4063-8294-4481ecedc043">

**Comment by sunnybeyond** [comment]
Not enough info far a case.
