### ISSUE TITLE
Feature Feedback

### ISSUE THREAD

**Issue by htetminwun** [beyond-btc/community#87]
would be better if the website shows correct available tokens or coins amounts and also balance on BNB testnet chian is showing 0 all the time 

would like to see more wallet connect options for different wallets soon
that's all for now , wish you all the best 

![image](https://github.com/user-attachments/assets/1dc1dc4b-82bc-467f-969a-128006269612)
![image](https://github.com/user-attachments/assets/03f90299-6b5f-4b27-97f1-38e099fb6b48)
![image](https://github.com/user-attachments/assets/cd99e94f-ebe2-40cb-b587-91059a169d88)

**Comment by sunnybeyond** [comment]
I do expect a bit more effort in a writeup than this, even though the cases are valid...
