### ISSUE TITLE
Feedback on the experience in the Beyond testnet

### ISSUE THREAD

**Issue by Carolmyst** [beyond-btc/community#91]
During my experience in the Beyond testnet, I encountered several challenges that I believe are important to share in order to improve the journey for users, especially those who are less familiar with the BTC network:

- Difficulty connecting Metamask:
I tried to connect my Metamask wallet to the protocol, but the application was unable to call the wallet. I spent several hours trying to resolve the issue without success. After switching to the Opera browser, I was finally able to connect Metamask, but this created another problem: the Unisat wallet, which had worked in the other browser, is not compatible with Opera. Switching between browsers can be frustrating and may deter new users.

- Lack of clear and step-by-step documentation:
One of the major difficulties I encountered was the absence of a clear guide on how to use the protocol. There isn’t a step-by-step tutorial that helps new users navigate between networks and use the faucets effectively. Most users are more familiar with networks like Ethereum and Solana, which offer a simpler and more direct experience. The inherent complexity of the BTC network can be a significant barrier for new users who are still learning, and a detailed guide would be of great help.

- Issues with faucets between networks:
In addition to the wallet connection difficulties, I also faced problems trying to send faucets between networks. This can be disheartening, especially for those who are starting and looking to effectively test the platform.

Suggestions:

- Develop a detailed and intuitive user guide, including instructions on how to connect different wallets and navigate between supported networks.
Improve application compatibility with various browsers, allowing users to use their preferred wallets without needing to switch between browsers.
- Facilitate the use of faucets and ensure that the process between networks is more transparent and straightforward.
I believe these improvements could make the Beyond protocol more accessible, especially for those starting their journey in the crypto world, and would provide a smoother and more satisfying experience.

**Comment by sunnybeyond** [comment]
Very suspect of this being written by ChatGPT.
