### ISSUE TITLE
[When I interact with the ₿eyond bridge...]: 

### ISSUE THREAD

**Issue by almuhajaraswada** [beyond-btc/community#93]
### Contact details

almuhajaraswad1@gmail.com

### What happened?

I bridged from the BTC network to Sepolia, and there was a problem with the BTC wallet and my wallet was not responding to transactions. 
![Screenshot 2024-10-18 195643](https://github.com/user-attachments/assets/a171d384-9639-4eae-a35d-259a07554887)

**Comment by sunnybeyond** [comment]
Not enough info to create a case with.
