### ISSUE TITLE
Incorrect Estimates and Bridge Errors

### ISSUE THREAD

**Issue by khoerunid** [beyond-btc/community#94]
### Contact details

https://x.com/copebloom

### What happened?

1. Inaccurate estimates. Before clicking 7 minutes, and after clicking 20 minutes.

![Screenshot_20241018_182614_Mises](https://github.com/user-attachments/assets/16dc25b8-2a75-4075-8b4f-20b6f23a9ea6)
![Screenshot_20241018_182622_Mises](https://github.com/user-attachments/assets/7497ccc2-4ede-4936-a8b5-992d3cb39434)

2. The bridge from TBTC to Sepolia doesn't work.

![Screenshot_20241018_185640_Mises](https://github.com/user-attachments/assets/9316f816-00db-497f-b418-65cc5085aff3)

Device : Samsung A54
Browser: Misses browser
Exstensi: Metamask and Unisat

### On which browser(s) did you encounter the issue?

Other (please specify)

**Comment by sunnybeyond** [comment]
Not enough info to create a case with.
