### ISSUE TITLE
[When I interact with the ₿eyond bridge...]: Connectivity 

### ISSUE THREAD

**Issue by PGabz** [beyond-btc/community#99]
### What happened?

I faced connectivity issues on my PC but it opened instantly on my phone. After several attempts, I managed to access it on my PC. I successfully claimed all my faucets, and approving beyond BTC on Sepolia Ethereum took under a minute. However, I couldn't bridge from Bitcoin Testnet to Sepolia Testnet. Despite my Bitcoin Testnet showing in my wallet, it didn't appear when needed. Bridging from Sepolia Testnet to Bitcoin Testnet was seamless and quick, and bridging from BNB to ETH was also swift. Overall, the website is excellent—smooth and fast—though improvements are needed for bridging BTC Testnet to Sepolia.

bc1pyl9a8q3xsptvcgzcwempdzz0e8eyvm5uatcnkhvrmrww94vx8f5qgndqam

**Comment by sunnybeyond** [comment]
Not enough info to create a case with.
